### PR TITLE
Support white addressable LED strips

### PR DESCRIPTION
**Pull request by Aircoookie**
Adds support for white-only addressable LED strips with 3 white LEDs per WS2811, like these:
https://de.aliexpress.com/item/1005004771896342.html
https://de.aliexpress.com/item/1005004092153344.html

Still draft, as code style can be improved and I also would like to add support for addressable CCT:
https://de.aliexpress.com/item/1005005004675542.html

### CODE REVIEW

**Comment by blazoncek** [comment]
I am in the process of adding UCS890x LEDs (16bit).
I have 8903 running but 8904 is giving me headaches as apparently something doesn't do bounds check and I see heap corruption.

Would you care to take a look? I'll publish UCS890x branch.

**Comment by blazoncek** [comment]
UCS890x has been solved by NeoPixelBrightnessBus patch.
See https://github.com/Makuna/NeoPixelBus/issues/638

**Comment by MichaelBMF** [comment]
Hi i'm new to WLED and thx for that great project!

This PR will add support for IC controlled CCT strips. But as far as i understand, this COB CCT addressable strip will still be not supported: 
https://www.btf-lighting.com/collections/fcob-led-strip/products/fcob-cct-ic-led-light-strip-addressable-576-leds-2700k-to-6500k-10mm-dc24v-flexible-high-density-cob-ra90. 

Perhaps on the weekend i have time for some coding. The part with new types and capabilities i  think i already understand. There is only need for an WS28xx type that only needs two channel for cw and ww i think.

**Comment by Aircoookie** [comment]
@MichaelBMF seems like these use 1 WS2811 for each zone, which is easier code wise than the 2 WS2811 for 3 zones arrangement. Will add support for these too (in a separate PR)

**Comment by blazoncek** [comment]
It seems there is a bug regarding RGBW strips.
```
{
	"seglc": [
		1,
		3,
		6
	]
}
```
is reported for 3 segments. Segment 1 contains WS2812 & SK6812 strips (spanning 2 GPIO), segment 2 only has SK6812 and segment 3 only has PWM White CCT. Segment 1 is a 2D segment (20x20). Bus 1 has 396 LEDs, bus 2 has 25 LEDs (SK6812, none for AW), bus 3 is PWM CCT (none for AW).

**Comment by Aircoookie** [comment]
> It seems there is a bug regarding RGBW strips.

Good catch! The second (RGB + white, lc 3) and third segment (white + cct, lc 6) here are as expected. However the first incorrectly reports RGB only.
This is not an issue about different strip types, but about `Segment::refreshLightCapabilities()` not taking into account 2D, it just checks start/stop (or X coordinates in 2D), so it will consiger segment 0 to be only the first 20 LEDs.
Mixing strip types within the same matrix is probably a niche use case, still capabilities should properly take 2D into account of course.

**Comment by blazoncek** [comment]
One more note: `Segment::refreshLightCapabilities()` does not take into account any mapping that has been done.

**Comment by blazoncek** [comment]
Yet another note: 2D segments may have "gaps" (see led-gap branch/PR) which may mask unused pixels (-1).

**Comment by blazoncek** [comment]
I have a fix that seems to work correctly for 1D, 2D and mix of 2D and 1D segments.
Ledmaps included.
Will be available in led-gaps branch.

**Comment by blazoncek** [comment]
This also resolves #2983

**Comment by snenyl** [comment]
I got white-only addressable LED strips with 3 white LEDs per WS2811 how do I enable this so the mapping is correct?

**Pull request merged**
