### PR TITLE
DMX Support for WLED

### PR DESCRIPTION
**Pull request by jwingefeld**
This adds DMX support to WLED using the MAX485 chip.
There are some things to consider or to look over:

- List of required libraries needs to be updated in the documentation or the ESP-Dmx library needs to be included. I don't know anything about the licensing stuff.
- I'll write a wiki page on the setup.
- Some kind of wiring diagram would be useful.
- The feature is disabled by default so it doesn't inflate the filesize and the experience of "regular" users
- i raised the EEPROM-Version from 14 to 15.
- versionString changed to 0.9.1-dmx. I don't know if this is the correct way to do it. Please change if needed.
- PAGE_SETTINGS is now parsed through settingsProcessor to dynamically include the menu item "DMX settings". This might break some HTML.
- i didn't touch any of the PIO stuff.

Other than that this should work just fine. However: here be dragons.

### CODE REVIEW

**Comment by Def3nder** [comment]
Hi @jwingefeld, 
could you please merge the actual master into your branch and push it back to Github ?

...this eliminates alle the files that actually you actually did not change, but were changed from @Aircoookie with the last commit.

Then the number of "changed files" would decrease and this could be merged without refactoring everything again.

Thx a lot.

**Comment by Aircoookie** [comment]
Thank you!
I will go over it once again and merge it tomorrow :)

**Comment by pille** [comment]
@jwingefeld: can you please elaborate on your goal in https://wled.discourse.group/t/dmx-roadmap/154

**Comment by pille** [comment]
@jwingefeld, i'm trying to use this code, but i fail, as my DMX lights stay off. can you please get in touch with me.

**Comment by jwingefeld** [comment]
oh, sorry. i don't look into the issues that often. Are you on discord? You can find me as JvPeek there.

**Comment by pille** [comment]
i'm only on discourse ;)
but i could make it work in the meantime.

**Pull request merged**
