### PR TITLE
Sync groups

### PR DESCRIPTION
**Pull request by blazoncek**
This could help solve #2136.
Not yet tested.

### CODE REVIEW

**Comment by blazoncek** [comment]
The real question is: do we enable all groups by default? For sending? For receiving? Or both?
Personally I have found that it may be better to have only  one group (i.e. 1) enabled by default for both send and receive.

**Comment by blazoncek** [comment]
Tested and working properly.
Older devices follow the master regardless of sending group (backwards compatible?).

**Comment by Aircoookie** [comment]
Awesome!
Will give it a try soon too.
Also believe that in a typical use case, having send and receive only enabled for the first group would make the most sense. Otherwise, once you want a new dedicated group, you'd need to reconfigure all existing devices to no longer receive/send on that group.

**Comment by Aircoookie** [comment]
Made a slight change so that old UDP packets are treated as group 1 only - that way it is easier to set up a new group without updating all existing instances.

Functionality is awesome!
One thing I noticed is that adding the options in xml.cpp causes a high dynamic string length (+260 bytes) due to `d.Sf.G1.checked=1;d.Sf.R1.checked=1;` and so on. This hasn't caused problems in my testing, still we might want to consider doing the bitshifting in JS, reducing the number of transmitted options from 16 to 2. We already do this with `FC()` and `Wd()` in time settings for the weekdays. Will implement this now :)

**Comment by Aircoookie** [comment]
Done. Also added a check if no sync group is enabled, in that case we don't need to send UDP at all, since it will be rejected by all recipients anyways (except for <0.13)

**Pull request merged**
