### PR TITLE
Old style multicolor christmas lights

### PR DESCRIPTION
**Pull request by fishbone-git**
One for later on.  This replicates old style multicolor christmas strings with 5 colours, either static (speed=0) or in a chase.  This is meant optimally for strings, but strips can look good with some spacing set.

### CODE REVIEW

**Comment by blazoncek** [comment]
You can replace Haloween (53) IMO.

**Comment by Aircoookie** [comment]
I believe this is very similar to the Colorful effect with max intensity and the C9 New palette. Probably not worth a standalone effect to add purple, the 5th color. Might add it as a new palette though :)

**Comment by blazoncek** [comment]
FYI It is possible to create a custom palette via JSON upload in 0.14.

**Comment by fishbone-git** [comment]
good tips. Thanks! 14 looks great so far almost looks like effects via usermods could be not far over the horizon (enumeration of ID looks like the big hurdle)

**Comment by blazoncek** [comment]
> looks like effects via usermods could be not far over the horizon (enumeration of ID looks like the big hurdle)

That was the intention of the rewrite. It may be possible to make a list of reserved IDs. But usermod effects are up to users (and a possible usermod setting).

**Pull request closed without merging**
