### PR TITLE
Adapting VL53L0X_gestures usermod for the WLED 0.13 release

### PR DESCRIPTION
**Pull request by eg321**
Removed longPressMacro call
  Fix debug calls
  Fix typos

### CODE REVIEW

**Comment by eg321** [comment]
Hi here,

my fork was out-of-sync by some reason. I've updated it, now it's in actual state, but there are some commits from master displayed in this PR. Anyway "Files changed" show my changes only.

**Comment by blazoncek** [comment]
Out of curiosity (since I bought 2 of this sensors recently) why did you remove "long press" action?

**Comment by eg321** [comment]
> Out of curiosity (since I bought 2 of this sensors recently) why did you remove "long press" action?

I was sure that nobody used that feature.
Unfortunately "applyMacro" used for "long press" was broken in last WLED version. Can't find how to fix it. If you have ideas, please share...

**Comment by blazoncek** [comment]
Thanks.

Please take a look at Rotary Encoder ALT (as it is most recent and Four Line Display as well) in 0_14 branch to see how to enhance this usermod to be fully runtime configurable (including I2C pins) and applying presets.

Pay attention to `readFromConfig()` function (and other new functions).

And please rebase the PR to 0_14 branch, not main.

**Comment by Aircoookie** [comment]
Merging. The problem with long press is probably just that it clashes with the "distance dimming" functionality.
Please submit another PR if you get around to make the mod runtime configurable :)

**Comment by blazoncek** [comment]
@eg321 could you update the usermod to take 2 sensors?

I found [this article](https://learn.adafruit.com/adafruit-vl53l0x-micro-lidar-distance-sensor-breakout/arduino-code) on how to set up two of them and have an idea on how to use them.

If by any chance you have the time you could as well add support for those in the Animated Staircase usermod?

**Comment by eg321** [comment]
> @eg321 could you update the usermod to take 2 sensors?
> 
> I found [this article](https://learn.adafruit.com/adafruit-vl53l0x-micro-lidar-distance-sensor-breakout/arduino-code) on how to set up two of them and have an idea on how to use them.
> 
> If by any chance you have the time you could as well add support for those in the Animated Staircase usermod?

Hi,
sorry, I'm quite overloaded with my current projects and cannot promise to take this in work soon.

Anyway, can you create separate issues for mentioned topics above and describe your scenarios please (if that ok in this repo)? Right now I don't understand why you need 2 TOF sensors and what you mean with Animated Staircase usermod.
I'll try to take it in work once will have a chance (or maybe someone else will contribute there?).

Thanks!

**Pull request merged**
