### PR TITLE
Usermod v2 http pull light control 0.0.4

### PR DESCRIPTION
**Pull request by roelbroersma**
Update of 0.0.3 but with SHA1 support for the HASH, which is better than the old FOWler hash which had a maximum of 10 digits.  SHA1 is supported on ESP32 and ESP8266 (even though it are different core libraries).

### CODE REVIEW

**Comment by blazoncek** [comment]
There are now 2 PRs for similar thing. Which is the correct one?

**Comment by roelbroersma** [comment]
This is the new version v.0.0.4,  the previous one is v.0.0.3.

You can first integrate version 0.0.3 and then this 0.0.4, which has as better hash method.  Maybe in future there will be a v0.0.5 :)

**Comment by roelbroersma** [comment]
> What would be the purpose of merging 0.0.3 first and then 0.0.4? Why not just 0.0.4?

Nothing, beside having some administrative history.
You can also close the request for v0.0.3 and do version v0.0.4.

**Comment by roelbroersma** [comment]
Hi @blazoncek , what do you propose I'll do when in the meantime I have updates?  I first did a pull-request for v.0.0.3,  then (even before that pull-request was merged), I did a new pull-request for v0.0.4  (this one).  And actually...  today I just made a v0.0.5 which fixes some invalid JSON handling and always releasing the buffer (which could have not been done in rare circumstances).

Do you want me to do a pull request for that? 🙄😃

**Comment by blazoncek** [comment]
If these are progressive updates I see no point in opening *different* PRs.
Just push your changes to your current branch and the PR will update automatically.

You can also close 0.0.3 for that matter.

**Comment by roelbroersma** [comment]
Closed because of the new v0.0.5.
See: https://github.com/Aircoookie/WLED/pull/3560

**Pull request closed without merging**
