### PR TITLE
multibutton / JSON MQTT support

### PR DESCRIPTION
**Pull request by evarsanyi**
For your consideration: A core change to add multiple inputs, runtime pin assignment, and adds MQTT message sending to the JSON API. Happy to refactor this into 2 PR's, fix any style issues I missed, or otherwise change. I very much appreciate the work you've done with WLED and I want to give some time back to the community!

There are detailed docs in README.md, I will be happy to merge these with the official docs and/or create a wiki page with info as desired. If this is all more appropriate for the filesystem branch I can easily rebase to that.

This code (and a basket of other features that are no longer needed with the recent SPIFFS/json/preset upgrades) started about a year ago when I abandoned keeping up with the 2812/scene support I'd added to Tasmota. I've been using the core of this (the changes to button.cc) on about 10 devices built into wall switches and other accent lighting since about March. I use the MQTT functions with Home Assistant. I refactored the original code when the filesystem branch was merged which left just the two core features: multiple input support and the ability to send arbitrary MQTT from a JSON API macro (now preset).

Here's a discourse description with the motivations: https://wled.discourse.group/t/multiple-buttons-macros-segments-json/258

This may also address Issue#62.

Some notes on the changes:

* Created an InputConfig struture with the input pin, type, and array of presets
  * WLED_INPUTS of these are allocated statically via WLED_GLOBAL
  * They are initialized in WLED::setup() from compiled in defaults (BTNPINx) and the cfg.json mechanism
    * inputEarlyConfig() sets the compiled in defaults
    * inputInit() initialized the pin I/O and instantiates the input state structures (in button.cpp), this is also where the stuck input logic got moved to
  * these replace buttonEnabled, macroButton, macroLongPress, and macroDoublePress internally
* button.cpp
  * This has a class that handles a single input, it is instantiated for each configured input with a reference to the InputConfig structure it uses
  * this only handles the PUSH and NONE types, it should be easy enough to add switch support
    * I have some debounced toggle switch routines I can incorporate in another PR, they also allow for double/triple flips
  * the touchpin logic works as before multiplexed with the first input
* cfg.cpp handles multiple inputs
  * maybe should change 'btn' to 'inp'?
  * maybe fold the pin field out of the array, it will only ever be 1 entry with this schema?
* Changed the UI functions to load/emit WLED_INPUTS worth of input macro preset mappings
  * did not make the ui adapt automatically to WLED_INPUTS, this might be worthwhile eventually
  * as it stands if you make WLED_INPUTS 4 the UI macros page will not fill in anything because those extra fields do not exist in the form (and the function gets an error)
* mqtt.cpp and json.cpp
  * if MQTT is enabled allows a JSON API feature that reads an array of messages to send while implementing the rest of the macro
  * this can be used to send messages on button presses or when presets change for other reasons

### CODE REVIEW

**Comment by Aircoookie** [comment]
Thank you very much for the huge PR :)
It will take a bit of time until I get to reviewing it, sorry about that.
Will get back to you in detail at some point soon!

**Comment by evarsanyi** [comment]
Thanks! I really like the refactoring done with the filesystem merge (it made everything so much cleaner). I'm happy to go further with the dynamic pin config for the inputs or switch it back to a static compile time config only if that's more what you'd prefer. The weakest part of this PR is the UI support, I just copy/pasta'd the macro settings on the frontend (its dynamic, at compile time, in the backend). I could make it dynamic if you think that's important (and/or add UI to configure the input pin mappings) -- but that sort of UI work seemed like a separate project so I just did the minimum in this one.

I have some toggle switch code I wrote for Tasmota I could integrate too as another PR to implement the 'wall switch' mode.

**Comment by ITqua** [comment]
Any updates on this? Looks like really needed feature, that many of us wants to have :)

**Comment by blazoncek** [comment]
> Any updates on this? Looks like really needed feature, that many of us wants to have :)

Multiple buttons are core feature since #1977, the PR to add MQTT (and a few other enhancements) #2011 is still in a review state.

**Comment by ITqua** [comment]
> > Any updates on this? Looks like really needed feature, that many of us wants to have :)
> 
> Multiple buttons are core feature since #1977, the PR to add MQTT (and a few other enhancements) #2011 is still in a review state.

Thanks for letting me know!
I've compiled and flashed the build from latest sources and yes, buttons support is here.
But now I don't see ability to call a custom macro (e.g. assign an action "switch to next preset" or "switch to prev. preset" for hardware button).

Any chance to get it back with MQTT support?

**Comment by blazoncek** [comment]
> But now I don't see ability to call a custom macro (e.g. assign an action "switch to next preset" or "switch to prev. preset" for hardware button).
> 
> Any chance to get it back with MQTT support?

The first feature is available in Time & Macros Settings page.
The second is still waiting to be merged to master.

**Comment by evarsanyi** [comment]
I'm willing to water this (get it current) but it seems there isn't much interest in the changes, my needs are met so maybe we should just close this so people don't keep asking about it?

**Comment by blazoncek** [comment]
All of the features are in WLED core since #2011. Closing

**Pull request closed without merging**
