### PR TITLE
Pin ArduinoFFT version

### PR DESCRIPTION
**Pull request by willmmiles**
The upstream repository has updated the develop branch to v2.0 which is not API compatible.  Pin the last commit before the new version was merged.

### CODE REVIEW

**Comment by blazoncek** [comment]
IMO we're better off accepting new API and modify AR usermod. @softhack007 your thoughts?

**Comment by willmmiles** [comment]
> IMO we're better off accepting new API and modify AR usermod.

I agree that we should update to the new version soon. I suggested this patch as a safe, short term fix as the GitHub CI system is now reporting build failures for all PRs, and clean checkouts won't build anymore either unless your local PlatformIO has already cached the old version.

**Comment by blazoncek** [comment]
Resolved by using release version 2.0.0 of ArduinoFFT.

**Comment by willmmiles** [comment]
Good enough for me - I didn't have hardware on hand to test any changes, I just wanted the CI to work :)

**Pull request closed without merging**
