### PR TITLE
Add ESP32 S2 Mini Board environment

### PR DESCRIPTION
**Pull request by LDprg**
Very much the same as lolin_s2_mini. However some HW pins mismatched and the board type too.

### CODE REVIEW

**Comment by LDprg** [comment]
Actually the lovely s2 mini config just works fine (only from source not from precompiled binary).

**Comment by eadmaster** [comment]
> only from source not from precompiled binary

you mean the binaries in the [releases page]( https://github.com/Aircoookie/WLED/releases)?

**Comment by LDprg** [comment]
yes

**Comment by eadmaster** [comment]
No problem, should i flash 
https://github.com/Aircoookie/WLED/releases/download/v0.14.4/WLED_0.14.4_ESP32-S2.bin

or

https://github.com/Aircoookie/WLED/releases/download/v0.15.0-b3/WLED_0.15.0-b3_ESP32-S2.bin

?

Last time i've tried the web server was working fine, but led controls were not working. Not sure if it is a wiring/voltage level issue with these small boards, but the same setup worked fine witb another esp8266 board.

**Comment by LDprg** [comment]
I did flash 0.15.0-b3.

**Comment by eadmaster** [comment]
the web server works fine, but i'm  getting some issues with the led control (blinking/cycling colors with no reason), are you using some level shifter?

I have a 30 leds strip and was working fine without level shifting on the other esp8266 board i have.

**Pull request closed without merging**
