### PR TITLE
Update esp32_multistrip usermod to fix compile errors

### PR DESCRIPTION
**Pull request by broccoliboy**
Update my usermod with CanShow function to track core NpbWrapper.h and fix compile errors caused by #1466. Have not tested on hardware yet.

### CODE REVIEW

**Comment by pszafer** [comment]
hi, with this branch second pin is not working for me and first it's a mess. half of the strip is working, second half is flickering, it seems like data from second strip is trying to overwrite data from first strip.

**Comment by andyshinn** [comment]
Do you have any other usermods or modifications? I just applied these changes manually to `master` and testing multiple segments and single segment seems fine.

**Comment by pszafer** [comment]
@andyshinn , no I don't.
I just adding
```
RgbColor rgb2 = RgbColor(c.G, c.R, c.B);
```
because I have two different strips.
I will try tonight to erase_flash and check if with "fresh" esp it's working

**Comment by pszafer** [comment]
with pre-erased flash it's working!

**Pull request merged**
