### PR TITLE
Tetris AI

### PR DESCRIPTION
**Pull request by muebau**
Adds an self playing Tetris effect based on a simple AI (polynomial).

### CODE REVIEW

**Comment by blazoncek** [comment]
Thank you.
You will need to rebase this to 0_15 branch.

**Comment by muebau** [comment]
;-) sounds good. I know how to do it with git at the command line but I have no clue how to get it in Github. Do you have a hint for me?

**Comment by muebau** [comment]
Thank you. By "your branch (not main!!!)" you mean "muebau/main"? (as I developed my mod at this branch)

If not, should I create a branch like muebau/tetris?

**Comment by blazoncek** [comment]
> Thank you. By "your branch (not main!!!)" you mean "muebau/main"? (as I developed my mod at this branch)
> 
> If not, should I create a branch like muebau/tetris?

You should have not.

Yes, make a new branch and PR from that. As described in the article.

**Comment by muebau** [comment]
Sorry for the delay. It has been a busy week.
I did like you told me. I think it should be better now.

https://github.com/Aircoookie/WLED/pull/3711

**Comment by blazoncek** [comment]
Closed in favour of #3711

**Pull request closed without merging**
