### PR TITLE
Sound reactive WLED routines

### PR DESCRIPTION
**Pull request by atuline**
I don't expect this to get merged . . . at least at this point.

I did, however, want to show you that we're working on basic sound reactivity for the ESP8266/32 and FFT sound reactivity for the ESP32.

We defined some extern variables in FX.h in order to access them from wled06_usermod.ino. Don't know if that's acceptable or not.

Just wanted to pass this along. If you have guidelines of what (not) to do, I'm sure we'd be happy to try and do that.

We're also going to issue a request to get more more sliders, especially for the FFT. Would be nice to have a slider exposed only if required by a routine.

### CODE REVIEW

**Comment by Aircoookie** [comment]
This is great! I will try it out in person and maybe I can merge it soon. Will have to obtain a mic though, would you rather recommend the INMP401 or MAX9814?

About the extern variables, that is fine for now, but before i merge it I would refector it to `wled22_sound.ino` and add some methods to FX.h as an interface.

Thank you for your hard work, I saw the "potato" video and it looked amazing. Can't wait to try it out myself!

**Comment by atuline** [comment]
I use the INMP401, while apleschu uses the MAX9814. Both seem to work fine. The I2S INMP441 is probably the best, however that will only run on the ESP32 (and I haven't played around with it).

Oh, and our Wiki (that I threw together yesterday) is at: https://github.com/atuline/WLED/wiki. It's got my notes on what I've done, important variables/structures, steps on flashing the binary and how to compile WLED from a scratch install of the Arduino IDE.

**Comment by hediondo1** [comment]
late night update the micro is not workink...switch back to bin release. @atuline

**Comment by luminxa** [comment]
Any updates on this?

**Comment by atuline** [comment]
> Any updates on this?

We've been in contact with Aircoookie and he intends to merge with our code, but he needs to re-write some of it prior to doing so. One of the major issues is with sliders. We've added 3 new sliders for the FFT code and it can get confusing for routines that don't need it. I believe Aircoookie is looking into dynamically visible sliders.

**Comment by PRO2XY** [comment]
@atuline , @apleschu and everyone else working towards this. I just wanted to appreciate the progress being made you people. Great work! 

I have @atuline 's repo flashed onto an ESP32 with 16 WS2812s. It compiled without any problem. All I had to do was add arduinoFFT in lib_deps, and uncomment the correct build environment. 

Loving the new ASound10 effect as of now :-)
Is there any discord group or similar where WLED folks hang around? I'd love to contribute with testing, if you'd be interested. 

Cheers!

**Comment by raoulteeuwen** [comment]
> Loving the new ASound10 effect as of now :-)

Any chance you can share a video, to have others see what they're missing :-)?

**Comment by atuline** [comment]
> @atuline , @apleschu and everyone else working towards this. I just wanted to appreciate the progress being made you people. Great work!
> 
> I have @atuline 's repo flashed onto an ESP32 with 16 WS2812s. It compiled without any problem. All I had to do was add arduinoFFT in lib_deps, and uncomment the correct build environment.
> 
> Loving the new ASound10 effect as of now :-)
> Is there any discord group or similar where WLED folks hang around? I'd love to contribute with testing, if you'd be interested.
> 
> Cheers!

Hi, the WLED Discord is at: https://discordapp.com/channels/473448917040758787/473449548279185408

**Comment by WolJG** [comment]
Hi, 
in the Sound Reactive WLED Wiki you tell about using 3.5mm Line In.
Can you pleas tell me more about this, how to connect.
Thank you very much

**Comment by THATDONFC** [comment]
Finally, we're getting somewhere!

**Comment by Iv711** [comment]
This is good news! When are you planning to release?

**Comment by apleschu** [comment]
“Release” will be when we have a few more 2D routines. At this very time one of our team members (@johnny5canuck) is implementing a few more that he had already prepared for just this moment and after that a beta release should not be long out. My guess is within the next 14 days we will have something in beta.

**Comment by CMaxim77** [comment]
Looking forward to this! Thanks for the work that has been done so far on this!

**Comment by ToXIc-Dev** [comment]
Am also looking forward to this being used into the master, looks promising.

**Comment by GrumpyMeow** [comment]
Adding support for the inmp441 with I2S was actually quite easy. Because of DMA it actually allows for some optimizations.

**Comment by atuline** [comment]
> Adding support for the inmp441 with I2S was actually quite easy. Because of DMA it actually allows for some optimizations.

I would love to see a pull with INMP441 support in it, or at least code I could add directly to my WLED fork.

**Comment by GrumpyMeow** [comment]
Hi Andrew,

I noticed code related to beat detection. But this code was commented-out.
I did some research on this subject. Funny enough I also came across your
Hartley transform libraries.
Out of curiosity, why did you choose to use FFT and not FHT?
I think it would be a great feature if the WLED parameters could be driven
by sound-parameters. Having the brightness driven by the amplitude of
sound.

What’s your thought on this?

Op ma 29 jun. 2020 om 14:32 schreef Andrew Tuline <notifications@github.com>

**Comment by atuline** [comment]
> Hi Andrew, I noticed code related to beat detection. But this code was commented-out. I did some research on this subject. Funny enough I also came across your Hartley transform libraries. Out of curiosity, why did you choose to use FFT and not FHT? I think it would be a great feature if the WLED parameters could be driven by sound-parameters. Having the brightness driven by the amplitude of sound. What’s your thought on this?

We could have long discussions on this. I've used the Open Music Labs FFT/FHT libraries in the past on the AVR, but didn't write them. In the case of WLED, we used the arduinoFFT library. I don't recall seeing an FHT library for the ESP's. 

In my sound reactive fork of WLED at https://github.com/atuline/WLED, we use volume/frequency for different things, including sine waves and Perlin Noise.

As for beat detection, I tested both a low frequency one I wrote as well as a volume one I wrote, and preferred the latter. What I really need is someone with some good signal processing chops.

In the meantime, if you'd like to add INMP441 support, I'd be happy to incorporate that. Feel free to join us in discussions on the WLED Discord server.

**Comment by TheZoker** [comment]
Any update, when this will be in beta?

**Review by HUAWEI-B315-32A7 — APPROVED** [review]

**Comment by patrickregis** [comment]
Hello,
is the sound reactive functionnality included in the present release please  0.10.2 ?
Regards, and BRAVO for this masterpiece that is WLED.

**Comment by atuline** [comment]
> Hello,
> is the sound reactive functionnality included in the present release please 0.10.2 ?
> Regards, and BRAVO for this masterpiece that is WLED.

The sound reactivity is only in our fork at https://github.com/atuline/WLED, which we do try and keep up to date with the latest pushes by AirCoookie.

**Comment by LukePrior** [comment]
Is there any plans to merge this into the main release or will it only be available through the fork?

**Comment by atuline** [comment]
> Is there any plans to merge this into the main release or will it only be available through the fork?

I'm afraid not for the forseeable future. That being said, one of our team members has done a remarkable job keeping our fork of WLED in sync with the main release.

**Comment by oscarsanchezmorales** [comment]
Hello, thanks for your project, it works perfectly, but I would like to activate the support for alexa in a wemos d1 mini and I am not sure which file I have to modify in vso or how to do it, a tutorial to compile your version in vso with the most basic files modifying would be of great help to me and the rest of the people.

**Comment by THATDONFC** [comment]
> Hello, thanks for your project, it works perfectly, but I would like to activate the support for alexa in a wemos d1 mini and I am not sure which file I have to modify in vso or how to do it, a tutorial to compile your version in vso with the most basic files modifying would be of great help to me and the rest of the people.

You'll need to comment out [the line](https://github.com/atuline/WLED/blob/master/wled00/wled.h#L30) that disables alexa support in `wled.h`

Change that to `//#define WLED_DISABLE_ALEXA         // saves 11kb`

**Pull request closed without merging**
