### PR TITLE
Animated Staircase Usermod

### PR DESCRIPTION
**Pull request by realrolfje**
A much requested usermod to animate a staircase, lighting each step as you walk up or down the stairs. See the [README](https://github.com/realrolfje/WLED/tree/feature/pir-staircase/usermods/Animated_Staircase) for a detailed explanation.

To see the effect of this usermod in action, check https://www.youtube.com/watch?v=6dLohE-6stQ

The usermod supports:
- PIR sensors
- Ultrasonic sensors
- Triggering through API
- Configuration through API

### CODE REVIEW

**Comment by williamsanter69** [comment]
Fantastic! Just what I needed for my project. Is it possible to enable/disable usermods in the UI?

**Comment by realrolfje** [comment]
Although I do see some changes that would indicate a move in that direction, the usermods can not be enabled/disabled in the UI at this time. This particular usermod can be enabled/disabled through an API call, but you do need to compile a version with this usermod in it first. Instructions are in the README.md.

**Comment by sagaardu** [comment]
What a great job, I would like to implement it in my ladder but I am very new to these things, could you detail a little more how the configuration of the segments is done and how it is saved in the preset?

Greetings

**Comment by Aircoookie** [comment]
Thank you very much for the usermod :)
I see you renamed the `pio` directory to `pio-scripts`, what is the reason for that? That name might be more intuitive thoguh, so I'd be willing to keep it. But you forgot the upload port in the nodemcuv2 environment :)
Will merge soon!

**Comment by realrolfje** [comment]
Good question. I am on a Mac, and for some reason, sometimes, the platformio plugin sees the "pio" folder earlier on the path than the pio executable. When that happens, the plugin says "pio not installed". After renaming the directory, this problem dissapeared. I'll have a look at the upload port, that might be an accidental commit from my local environment.

I noticed that other plugins, and the dev branch, use a `plaformio_override.ini` file and has the usermods included in the `usermod_list.cpp` so that copying the override file enables the usermod. If you prefer that, I can change the code to match that pattern, just let me know.

**Comment by realrolfje** [comment]
> What a great job, I would like to implement it in my ladder but I am very new to these things, could you detail a little more how the configuration of the segments is done and how it is saved in the preset and how do you integrate it in HA??

Hi Sagaardu, you set up the segments to match the steps. The bottom step is segment 0, one step higher is segment 1, and so on.

The settings of the usermod are stored in flash, you don't need to worry about that. Everything integrates with WLED, so saving a setting should work as expected.

Integration with Home Assistent depends on what you want to do, and I don't know Home Assistent that well. The usermod supports:
- Triggering the animation with a json (which can be sent from HA)
- Setting the animation speed and time with json (again, can be sent from HA)

Any other WLED setting can be controlled from HA as well, for information on that I can advise you to go to the WLED discourse, where there are a lot of nice people who can help you with installing WLED and setting everything up.

Have fun!

**Comment by sagaardu** [comment]
Is there any limitation on the number of steps that can be configured?

**Comment by realrolfje** [comment]
Hi sagaadu, the number of steps is limited by the memory of your microcontroller. If you use an ESP32, you can have more steps. Please see https://wled.discourse.group/t/segments-whats-the-real-maximum/116 (and ask your questions in that discourse group, it much bettern than here on github ;-) )

**Comment by sagaardu** [comment]
Hi realrolfje,

I see that the project is not accessible, has it been abandoned?

Greetings

**Comment by realrolfje** [comment]
On the contrary: It is very much alive and integrated into the development branch of the official WLED project:
https://github.com/Aircoookie/WLED/tree/dev/usermods/Animated_Staircase

Have fun!

**Comment by dinamicus** [comment]
the usermode is really nice appreciate it. is it possible or where in the code i can change to keep the first and last segments unchangeable. for example 1 and 10 segments are always light up and 2-9 start to light up by detection by PIR sensors

**Comment by realrolfje** [comment]
Hello dinamicus, you can find the source code in WLED/usermods/Animated_Staircase/Animated_Staircase.h when you clone the dev branch of WLED. For further discussion I'd like to point out [the excelent discourse wled usergroup](https://wled.discourse.group/t/fully-fledged-staircase-implementation/2182) where you can contact many users and developers for detailed implementation questions just like this.

**Comment by itsboo07** [comment]
i wanted to do somthing similar to this using esp32 and wled
https://www.youtube.com/watch?v=X8vHWPlUJSw&ab_channel=tinker.fun
could anyone help me out. im intrested in vertical lighting not step by step horizontal lighting.

**Comment by DonEugraf** [comment]
> i wanted to do somthing similar to this using esp32 and wled
> https://www.youtube.com/watch?v=X8vHWPlUJSw&ab_channel=tinker.fun
> could anyone help me out. im intrested in vertical lighting not step by step horizontal lighting.

Is there an available way to do this liniar setup yet? Or can it be achieved by setting number of led's as number steps?

**Pull request merged**
