### PR TITLE
compile warning fix

### PR DESCRIPTION
**Pull request by ingDIY**
added check for custom compile user defines, otherwise warning message are generated for custom build with DEFAULT_LED_TYPE or DEFAULT_LED_COUNT defined

### CODE REVIEW

**Comment by blazoncek** [comment]
Defining LED outputs was redesigned in 0.15.0-b6.
This PR is irrelevant.

**Comment by softhack007** [comment]
@ingDIY you can already use these defines for custom-compile overrides of pixel counts, LED type, and LED pins:

https://github.com/Aircoookie/WLED/blob/e9d2182390d43d7dd25492f6555d082280e79b3b/wled00/FX_fcn.cpp#L32-L46

**Comment by softhack007** [comment]
From what I see in the code, it shouldn't be necessary to override DEFAULT_LED_TYPE or DEFAULT_LED_COUNT.

Closing PR without merge.

**Comment by ingDIY** [comment]
> @ingDIY you can already use these defines for custom-compile overrides of pixel counts, LED type, and LED pins:
> 
> https://github.com/Aircoookie/WLED/blob/e9d2182390d43d7dd25492f6555d082280e79b3b/wled00/FX_fcn.cpp#L32-L46

OK thanks. Sorry but it's quite hard to track all these code changes. So the #defines i fixed are old and will be removed?

I based my modification following [WLED compile helper YAML](https://wled-compile.github.io)
and in the generated YAML it is still using
-D DEFAULT_LED_COUNT=50
-D DEFAULT_LED_TYPE=TYPE_WS2812_RGB

so please could you help me to better understand what custom define should I use?

**Pull request closed without merging**
