### PR TITLE
Update FX.cpp because of compile issue.

### PR DESCRIPTION
**Pull request by larryl79**
solution for ambiguous overload for 'operator==' error message

### CODE REVIEW

**Comment by blazoncek** [comment]
Please rebase this for 0_15 branch.

**Comment by softhack007** [comment]
I'm wondering if you are using some exotic build environment or not recommended library versions. I've never seen this warning.

'CRGB::Black' is an enum from the 'CRGB' object, casting it to "CRGB" again should have zero effect.

**Comment by softhack007** [comment]
CRGB::Black is not used in the matrix effect of `0_15` any more.


Closing this PR as its not applicable in 0_15. The reported problem is not happening in official builds of `main`, Any errors reported in FX.cpp would not depend on usermods in a different compilation unit.

**Comment by larryl79** [comment]
> I'm wondering if you are using some exotic build environment or not recommended library versions. I've never seen this warning.
> 
> 'CRGB::Black' is an enum from the 'CRGB' object, casting it to "CRGB" again should have zero effect. Same for `pix` and `oldSpawnColor` - they are all "CRGB" already.

No, I just freshly downloaded the repo, and tried compile. I had about 400 warnings, and 2 errors as mentioned. Then I got the platformio override file from usermods folder. When I done it I never thought to publicate it, so I didn't done any pics, or evidences. After when I finished with the compile with usermods then I thought to add it.

**Pull request closed without merging**
