### PR TITLE
add TM1829 support

### PR DESCRIPTION
**Pull request by h3ndrik**
Provide TM1829 support.
Similar to TM1814. This is an adressable RGB 12V led strip. This type is already supported by NeoPixelBus.

### CODE REVIEW

**Comment by blazoncek** [comment]
Unfortunately I have no way of testing this but it looks clean and to the point.
Approved.

**Comment by blazoncek** [comment]
Question regarding off-refresh.
TM1814 requires so called "off-refresh" which is sending data to the chip also in WLED off state (sending black color similar to static/solid mode). Does TM1829 also require such signal to prevent the chip to enter demo mode?

**Comment by blazoncek** [comment]
Looks like this is going to make it into WLED via #2737

**Comment by Aircoookie** [comment]
Now found its way into main :)

**Pull request closed without merging**
