### PR TITLE
Updating pxmagic and WLED UI

### PR DESCRIPTION
**Pull request by ajotanc**
Updating pxmagic and inserting it in the WLED UI with option to enable and disable.

### CODE REVIEW

**Comment by blazoncek** [comment]
I've briefly tested this and have a few remarks (this is not a full review).

1. First off, PXM or Pixel Magic button is inappropriate and IMO does not belong to the button bar.
Screenshot 2023-07-22 at 12 21 41
2. There is a lot of empty space at the top and the close button is missing (is rendered behind PXM content)
Screenshot 2023-07-22 at 12 24 50
3. When saving a preset, presets are reloaded **before** the actual preset is saved.
Screenshot 2023-07-22 at 12 19 01
4. PXM tool is reloaded *every* time it is activated which is a waste of resources.
5. Istead of displaying empty "Select a choice" make uploading an image a default behaviour. Only display drop-down selector if there are actual images stored on device.
Screenshot 2023-07-22 at 12 25 40
6. Making "Individual" as a default *Pattern* is potentially problematic as the JSON size will increase beyond usability.
7. Make sure you use tabs or spaces for indentation as appropriate for each file.

And honestly I do not see any reason to store images on the device as it only consumes FS space (image is stored in JSON format in preset) unless there was a usermod for displaying images in which case this tool would be obsolete.

**Comment by blazoncek** [comment]
Any news or updates @ajotanc ?

**Comment by blazoncek** [comment]
@ajotanc ?

**Comment by ajotanc** [comment]
> @ajotanc ?

I had some personal problems, that's why I wasn't giving feedback, these days I'll see if I can update it and see what can be improved!

**Comment by blazoncek** [comment]
Hi @ajotanc,

When you'll be updating this PR/tool, please add documentation in a similar way as was done for PixelArt Converter.
https://kno.wled.ge/features/pixel-art-converter/

**Comment by ajotanc** [comment]
> Hi @ajotanc,
> 
> When you'll be updating this PR/tool, please add documentation in a similar way as was done for PixelArt Converter. https://kno.wled.ge/features/pixel-art-converter/

How do I deal with this documentation issue? I'll go back and look at it today. I believe I already uploaded an update today

**Comment by blazoncek** [comment]
> How do I deal with this documentation issue? I'll go back and look at it today. I believe I already uploaded an update today

Fork WLED-Docs, add description in relevant .md files nad then make a PR. Similar process as in main WLED repo.
@wled-faq or @dosipod or @scottrbailey may be able to help you better.

**Comment by blazoncek** [comment]
My suggestion would be to move the button in color/palette tab. Like so:
Screenshot 2023-10-15 at 21 53 08
Or on the other side next to +.

**Comment by dosipod** [comment]
> > Hi @ajotanc,
> > When you'll be updating this PR/tool, please add documentation in a similar way as was done for PixelArt Converter. https://kno.wled.ge/features/pixel-art-converter/
> 
> How do I deal with this documentation issue? I'll go back and look at it today. I believe I already uploaded an update today
@ajotanc
Hey , It is very simple to do docs as you already made a video which i prefer but KB is mostly done with pictures  , i have made  a draft from the doc of existing tool . located here https://github.com/dosipod/WLED-Docs/blob/master/docs/features/pxmagic.md . once your PR is finalize then we can finalize the doc  for it along with pics ,video demo .etc  . Does not harm to actually have the same instruction listed on both your site and KB . In all cases an instruction on your github page might be enough and more practical for faster updates as this is basically an external tool   but that would mean you have to maintain an updated docs once you do a change as we have no write access to your repo  to modify that

**Comment by ajotanc** [comment]
> > > Hi @ajotanc,
> > > When you'll be updating this PR/tool, please add documentation in a similar way as was done for PixelArt Converter. https://kno.wled.ge/features/pixel-art-converter/
> > 
> > 
> > How do I deal with this documentation issue? I'll go back and look at it today. I believe I already uploaded an update today
> > @ajotanc
> > Hey , It is very simple to do docs as you already made a video which i prefer but KB is mostly done with pictures  , i have made  a draft from the doc of existing tool . located here https://github.com/dosipod/WLED-Docs/blob/master/docs/features/pxmagic.md . once your PR is finalize then we can finalize the doc  for it along with pics ,video demo .etc  . Does not harm to actually have the same instruction listed on both your site and KB . In all cases an instruction on your github page might be enough and more practical for faster updates as this is basically an external tool   but that would mean you have to maintain an updated docs once you do a change as we have no write access to your repo  to modify that

I will do this by completing what was done, I ended up not touching it yet to make it functional first in the WLED UI and thus make it complete.

But I took a look at what was done and it was super interesting, I think I just need to complete it, it's very interesting how it was done.

**Pull request merged**
