### PR TITLE
WIP: Added DMX mode effect segments #2325

### PR DESCRIPTION
**Pull request by mxklb**
These are changes for a new DMX_MODE_EFFECT_SEGEMENTS (a modified version of DMX_MODE_EFFECT).

Actually this only implements none GUI stuff to be able to control stripe segment effects individually via E1.31 DMX signals.

Each segment uses 11|13 DMX addresses. This mode utilizes [segments * 11|13] DMX adresses in one universe.

ToDo:

- [ ] add UI, docs and config stuff etc ..
- [ ] make DMX_MODE_EFFECT_SEGEMENTS stand alone (actually it's a compile option for DMX_MODE_EFFECT) -TBD
- [ ] final testings, quality check.

### CODE REVIEW

**Comment by mxklb** [comment]
I'll do the missing parts if I find time to do so in near future ..

@Aircoookie Do you think that this should be a modified version of DMX_MODE_EFFECT (maybe config via simple checkbox) or a complete new DMX_MODE_EFFECT_SEGEMENTS to be select as one of the other DMX modes? If you give me that input, I''l try to deliver the missing UI implementations .. cheers

**Comment by blazoncek** [comment]
Please use [these](https://github.com/Aircoookie/WLED/wiki/How-to-properly-submit-a-PR) instructions for making a PR.
If you want to discuss possible solutions convert this PR to draft.

**Comment by mxklb** [comment]
Okay I checked the instructions, expect making a new branch with squashed commits, everything looks as described.
I'll squash commit here into another branch when ready, is there anything else I've formally missed?

How to make a draft, of cause this actually is a draft :+1:

**Comment by blazoncek** [comment]
Please do not change `platformio.ini`. If you need custom PIO environments create `platformio_override.ini`.

**Comment by mxklb** [comment]
Yes, sorry this was my mistake, it should be reverted. I think about deleting and creating a new PR following exactly the instructions you posted. This looks more better. Actual state of implementation is still not ready for review. I'm sorry for this .. I'm further working on this the next days ..

**Pull request closed without merging**
