### PR TITLE
Buttons: Trigger on button press (instead of release) if all configured presets are the same

### PR DESCRIPTION
**Pull request by Sebbb**
Hello,

this addresses #3189. It works well for me, but I'm not sure if it doesn't maybe need additional debouncing code with some switches.

### CODE REVIEW

**Comment by blazoncek** [comment]
Thank you.
Would you be so kind and also add the info (PR) about same presets causing such behaviour to [WLED docs](https://github.com/aircoookie/WLED-docs)?

**Comment by Sebbb** [comment]
Hi,

I never experienced issues with that, for me it works perfectly reliable. Maybe because that button check routine is only executed every few milliseconds (?) to check the button state and does not trigger an interrupt.

However, I'm definitely not a good programmer and probably wouldn't be able to add that, if it's needed :(

Sebastian

**Comment by Aircoookie** [comment]
Added a slightly hacky debounce logic, should work fine though. 
On release it only reset `buttonPressedBefore` after 50 ms of uninterrupted released, and thus block further presses until the button has been released properly.

**Comment by softhack007** [comment]
> Added a slightly hacky debounce logic,

Thanks @Aircoookie, I think this will do the trick 👍

**Comment by Sebbb** [comment]
@Aircoookie I just compiled and tried your changes, works well :)

**Pull request merged**
