### PR TITLE
BH1750 upgrades

### PR DESCRIPTION
**Pull request by albarlow**
Moved the definitions into the main usermods_list.cpp instead of having a section to copy across.

Added Home Assistant Discovery topic for light sensor.  This is toggleable from the usermod menu.

### CODE REVIEW

**Comment by blazoncek** [comment]
Can you do the same things you did in BME280 usermod, please?

**Comment by albarlow** [comment]
Just working on this...there are a number of `'D` values that can be defined at compile time, but they can be set in the Usermod menu.  Given that you expressed a preference to remove compile-time variables, should I take those out of the Readme?  Or is the fact that they are set in `platformio.ini`, not in the code itself enough to make it okay?

**Comment by albarlow** [comment]
For the meantime, I have left the information about compile-time options in the readme.  I've implemented the pin manager, F() for strings, added API call for reading illuminance.

**Comment by blazoncek** [comment]
Compile time options are still welcome (to set a default values) but all of them should be able to be overridden using configuration.
Will have a look later of the changes.

**Comment by blazoncek** [comment]
Looks like there is an error in recent update to the usermod.
#2844

**Pull request merged**
