### PR TITLE
Tetris (falling bricks) effect & Colortwinkles low brightness fix.

### PR DESCRIPTION
**Pull request by blazoncek**
Added Tetris like effect (falling bricks) and fixed Colortwinkles low brightness error.
For Tetris like effect intensity should be 0 otherwise all bricks are the same length determined by intensity slider.
Similarly if speed slider is 0 individual brick speed is randomly determined.

### CODE REVIEW

**Comment by tonyn0** [comment]
Great work!

**Review by pierrebeitz — COMMENTED** [review]
Thanks for that contribution. If i were to review this, it would help me tremenduously if there was a description or even a screencast/video of how exactly this effect should look like.
I think it would also make sense to separate the brightness fix and the tetris-effect in separate PRs. That way they could be merged independently (and i'd love some enhancement onlow brightness twinkles! ❤️)

**Comment by blazoncek** [comment]
Here you go:
https://youtu.be/ps3KB348Z1s

**Comment by blazoncek** [comment]
> Thanks for that contribution. If i were to review this, it would help me tremenduously if there was a description or even a screencast/video of how exactly this effect should look like.
> I think it would also make sense to separate the brightness fix and the tetris-effect in separate PRs. That way they could be merged independently (and i'd love some enhancement onlow brightness twinkles! ❤️)

Colortwinkles was a "by the way" fix. Sorry about that. Does fit in though. ;)

**Comment by Aircoookie** [comment]
Looks absolutely amazing, thank you! Will review + merge tonight!

**Comment by blazoncek** [comment]
> Looks absolutely amazing, thank you! Will review + merge tonight!

You can increase the speed (both slider and max random) up to 2x while merging.

**Comment by Doyle4** [comment]
This looks amazing and has given me so many more ideas! Thanks WLED people :)

**Pull request merged**
