### PR TITLE
Dynamic LED map creation from JSON file

### PR DESCRIPTION
**Pull request by blazoncek**
/ledmap.json in format {"map":[4,3,2,1,...]}.

Used for rearranging LEDs (matrices, awkward placement, ...)

### CODE REVIEW

**Comment by JakeShirley** [comment]
@blazoncek I was working on a recent change to allow me to "ignore" one of my LEDs (I over-extended one strip so a single LED in the middle of my whole run is occluded).  This change should allow for that right?

**Comment by blazoncek** [comment]
> 
> @blazoncek I was working on a recent change to allow me to "ignore" one of my LEDs (I over-extended one strip so a single LED in the middle of my whole run is occluded). This change should allow for that right?

Not sure if I understand your issue correctly, but this functionality is not meant for "ignoring" pixels but for rearranging them on physical layer.

**Comment by JakeShirley** [comment]
Hypothetically you could omit an LED in the index list right?

**Comment by bazzer2** [comment]
I've just found this, looks to be just what I need!
I created /ledmap.json with the defaults from the example in FX_fcn.cpp (the second example doesn't have the closing wiggly brace) but I cannot get wled to read the map at all. 

Am I missing something more obvious?

**Comment by Legsmaniac** [comment]
You could omit a mid-LED using Segments.
Say you had 64 LEDs,  -
Set Segment 0 Start led 0 Stop led 32
Set Segment 1 Start led 33 Stop led 64
The 33rd LED will then remain off.

**Pull request merged**
