### PR TITLE
Usermod:  httpPullLightControl v0.0.5 (supersede v0.0.4)

### PR DESCRIPTION
**Pull request by roelbroersma**
Some changes after extensive testing. Now it will not break the runtime of WLED when there is invalid JSON.

### CODE REVIEW

**Comment by roelbroersma** [comment]
This one superseeds https://github.com/Aircoookie/WLED/pull/3527

**Comment by roelbroersma** [comment]
Excuse,

I thought (according to the docs: https://github.com/Aircoookie/WLED/wiki/How-to-properly-submit-a-PR ) that I needed to do a PR with only ‘1 commit with all of the merged changes’.

However v0.0.5 is quite solid now. We did a lot of testing and more than 60 units are running it over the world :)

If there will be a new v0.0.6 in let’s say 1 year from now, do you want me to do that in a PR then?

**Comment by blazoncek** [comment]
Guidelines are there for 1st submission. If changes are requested or bugs are found or new features are added there is no need to open a new PR, just push new commits to the branch used for PR. PR will be updated accordingly.
When a PR is closed (merged or otherwise) you will need to open a new PR if you want to introduce new features.

**Comment by blazoncek** [comment]
Please update PR (pull, fix, push) and rebase to 0_14_2 branch.

**Comment by roelbroersma** [comment]
> Please update PR (pull, fix, push) and rebase to 0_14_2 branch.

I just did, it is now up-to-date with the WLED/main, which is 0_14_2.

Can you accept this pull request so it will be really IN there?  I already had to fix a merge-conflict because of a Dusk_Dawn usermod which was having Usermod_ID 43  (and we had it also). So moved them to 44.
If you can accept the PR, it will be in there and we don't have that anymore.  All major changes and testing is done and don't see any need for a v0.0.6 in near future..

**Pull request merged**
