### PR TITLE
Add ArtPoll support

### PR DESCRIPTION
**Pull request by 4lloyd**
This PR adds support for ArtPoll and ArtPollReply. This solves #417.

At the moment the OEM and ESTA manufacturer code are set to zero. Someone of the WLED team may request these codes, so the device will show up as WLED in lighting consoles. This is not a must for the code to work, but more of a "nice to have".

These codes can be requested via:
- OEM code: https://art-net.org.uk/join-the-club/oem-code-application/
- ESTA manufacturer code: https://tsp.esta.org/tsp/working_groups/CP/mfctrIDs.php

The changes were tested on the esp32dev and esp8266_2m platform.

Parts of the code are inspired by the code of: https://github.com/hideakitai/ArtNet. That library also has a MIT license.

### CODE REVIEW

**Comment by Aircoookie** [comment]
Thank you very much! I will likely merge this after #2610

**Comment by erhan-** [comment]
Hello everyone, seems like there are some good news. https://github.com/Aircoookie/WLED/pull/2737 is merged. Will these changes be also merged now as told in https://github.com/Aircoookie/WLED/issues/417#issuecomment-1166325693 ?

Same for https://github.com/Aircoookie/WLED/pull/2619

Thanks for your contribution and help.

**Comment by Aircoookie** [comment]
Hey, I just pushed a small change, by allocating ArtPollReply on the stack when needed, we can save precious global heap RAM.
Since I lack host software that supports ArtPoll, please test if it still works as intended if you have time.

**Comment by 4lloyd** [comment]
> Hey, I just pushed a small change, by allocating ArtPollReply on the stack when needed, we can save precious global heap RAM. Since I lack host software that supports ArtPoll, please test if it still works as intended if you have time.

I tried the change and Art-Net is still working 👍

**Pull request merged**
