### PR TITLE
Date controlled timed presets.

### PR DESCRIPTION
**Pull request by blazoncek**
Can fulfill #2129 (at least partially)

### CODE REVIEW

**Comment by Aircoookie** [comment]
Looks good, though I'm experiencing a problem with the Sunset table row no longer being added :( Will look into that more.

**Comment by Aircoookie** [comment]
Now it can fulfill #2129 completely :)

**Comment by blazoncek** [comment]
Screenshot 2022-01-01 at 13 26 45
Hmmmm. Not getting an icon.
macOS 10.14.6 + FireFox 95.0.2
iPhone/iPad 15.2 + Safari

**Comment by blazoncek** [comment]
Substituted with `&#x2715;`

**Pull request merged**
