### PR TITLE
FX particle system

### PR DESCRIPTION
**Pull request by DedeHai**
finally ready to merge particle system and particle animations.
plz check it and add suggestions/comments

### CODE REVIEW

**Comment by DedeHai** [comment]
hm, something went wrong, I dont want to PR this into main.

**Comment by blazoncek** [comment]
You should've followed [Wiki](https://github.com/Aircoookie/WLED/wiki/How-to-properly-submit-a-PR) and squashed the commit.

**Comment by DedeHai** [comment]
> You should've followed [Wiki](https://github.com/Aircoookie/WLED/wiki/How-to-properly-submit-a-PR) and squashed the commit.

I really tried :) I followed exactly that, I used 'git merge --squash FXparticleSystem' but after this the 'git commit' said 'nothing to commit' so no Idea what went wrong there.

**Comment by blazoncek** [comment]
I will also require you to undo `platformio.ini` change and manage wihitespace in a consistent manner (also remove any non-essential whitespace change).

**Comment by DedeHai** [comment]
Ok, I will look at that. I really don't mind if you close these PRs, I can see that I squash my branch first and to it properly this time, will save you some work.

**Comment by DedeHai** [comment]
I made a squashed version. https://github.com/DedeHai/WLED/tree/FXparticleSystemSquash

**Pull request closed without merging**
