### PR TITLE
Add WLED_AUTOSEGMENTS compile flag

### PR DESCRIPTION
**Pull request by PaoloTK**
Add flag to enable setting "Make a segment for each output" at compile.

### CODE REVIEW

**Comment by blazoncek** [comment]
If you don't mind I think WLED_OUTPUT_SEGMENTS or WLED_OUTPUT_AUTOSEGMENTS or WLED_CREATE_AUTOSEGMENTS or perhaps just WLED_AUTOSEGMENTS would be more appropriate.

**Comment by PaoloTK** [comment]
> If you don't mind I think WLED_OUTPUT_SEGMENTS or WLED_OUTPUT_AUTOSEGMENTS or WLED_CREATE_AUTOSEGMENTS or perhaps just WLED_AUTOSEGMENTS would be more appropriate.

Sure, I like 2nd and 4th the most but your call.

**Comment by blazoncek** [comment]
I like the simplicity of the last one too.

**Review by blazoncek — APPROVED** [review]
Approved from my side.

**Pull request merged**
