### PR TITLE
Perceptual brightness usermod

### PR DESCRIPTION
**Pull request by obar**
This usermod lets you make changes to WLED global brightness in 'steps' that are evenly spaced to the human eye.

It lets the user define how many brightness steps to use (up to 32 by default) and what the maximum brightness should be. It also allows for skipping steps at the beginning and end of the range.

The usermod provides JSON API commands to step up and down in brightness, `{"pb":"+"}` and `{"pb":"-"}` respectively. It also provides commands to cycle brightness on a button hold, changing directions after a brief button release or optionally changing directions after reaching an extreme without a button release, `{"pb":"/"}` and `{"pb":"~"}` respectively.

### CODE REVIEW

**Comment by DedeHai** [comment]
thanks for contributing!
question: how is this different to the setting "use gamma correction for brightness"? It uses the CIE brightness formula.

**Comment by obar** [comment]
Oh that's interesting. Yeah the 'gamma for brightness' is computing brightness _basically_ the same way as this usermod. I'm struggling to recreate the button functionality I've got here without the usermod though. Is there a way to set lower/upper bound and step size in the API brightness command? Ideally I wouldn't want the gamma-adjusted brightness to go below 60 or above 160 on my setup. It seems with this gamma-adjusted brightness there are many low values which aren't really running.

It could be that my usermod's useful bit is press-and-hold button handling for brightness, with max/min/step size and the brightness cycling variations. Or does that make sense as an API extension and not a usermod?

**Comment by DedeHai** [comment]
I am not familiar enough with JSON commands to say if it is possible. The press end hold for brightness already exists, you just assign a preset to increase or decrease brightness with a defined step size and assign that to "long press" of the button (which still may have a bug, as discussed on discord). So the only thing missing would be to set upper and lower limits, correct?

**Comment by blazoncek** [comment]
`"bri":"w60~160~5"`
Buttons 1 and up, have repeating ability built in.

**Comment by obar** [comment]
Hmm, I tried exactly that API command in a preset and it doesn't work, from 0_15 branch. It works for you @blazoncek?

**Comment by blazoncek** [comment]
Looks like it is not working for "bri". You can file a bug report.

**Comment by blazoncek** [comment]
Similar to #3605

**Comment by blazoncek** [comment]
I have a generic fix. The API is `{"bri":"60~160w~5"}`.
The previous example is not valid any way.

**Comment by obar** [comment]
I just applied your 52e08d2 commit and tried it out with and without wrapping for brightness. Works perfectly! Between that and the gamma correction for brightness feature, my usermod isn't adding much :grin: Will close the pull request. Thanks!

**Pull request closed without merging**
