### PR TITLE
Bugfix/adc analog audio reactive issue #4345

### PR DESCRIPTION
**Pull request by pjkerly**
Bug Fixes for Issue https://github.com/Aircoookie/WLED/issues/4345 - Analog Microphone audio source shows ADC analog - quiet after enable (audioreactive usermod)

### CODE REVIEW

**Comment by netmindz** [comment]
Not 100% sure what you have done wrong with your PR as it contains very old commits as well as your recent commit. I'm not sure if your branch is just out of date or taken as a branch from the wrong source.

It might be best if you create a fresh branch and cherry-pick your commit into that. 

Would you prefer this to be done against MoonModules in the first instance @softhack007 given that's upstream for this usermod?

**Comment by pjkerly** [comment]
The instructions for PRs said to use branch  0_15 ... I see that there are also branches main and  0_15_0 .  Is 0_15 the correct branch to use?  I can pull a fresh copy.  I can also get a copy of MoonModules.  Is there a particular branch to use?

**Comment by pjkerly** [comment]
Closing this pull request ... will update later.

**Comment by netmindz** [comment]
From MoonModules, please branch mdev

**Pull request closed without merging**
