### PR TITLE
MQTT Authentication Support

### PR DESCRIPTION
**Pull request by timothybrown**
**EEPROM**
I’ve added three new 40 byte blocks and one 5 byte block to the EEPROM section for storage of the username, password, client ID and port. I don’t know if you want to map these somewhere else, so I just used to the next contiguous free block. The EEPROM version flag was moved from 10 to 11.

**MQTT Client ID**
I changed the way the client ID is generated. It now defaults to the string *WLED-* plus the last six digits of the MAC address. (This puts it inline with other projects.)

Added 40 character field for the client ID in the web UI. (This is important if you have a whitelist on your broker.) Leaving the field blank will return it to the auto-generated client ID.

**MQTT Authentication**
Added 40 character fields in the web UI for the username and password. If the fields are left blank authentication will be disabled.

**MQTT Port**
Added a 5 character field to the web UI for the broker port. Leaving the field blank will restore the default port.

Removed the hardcoded `#define` that previously held the port and replaced it with a `char[6]` array.

*TODO:* Validate the user input so only digits 0-9 can be submitted from the web form.

**PlatformIO**
Changed the default *platform* from Arduino Core to 2.4.2 to 2.5.0 to fix build issues.

**Misc**
It appears my editor (Atom) automatically stripped errant spaces from blank lines in the source, so that’s a bonus I guess!

mqttwled

### CODE REVIEW

**Comment by sunfos2019** [comment]
Once again thank you very much for your project - great clean job.
And thanks for adding long waited mqtt authentication support) Just checked and flashed last code - it seems authentication works fine, autodiscovery too. WLED appears in Home Assistant via Mosquitto. But I find one thing that doesn't work correctly - when I switch on/off WLED from Home Assistant wled web interface shows that leds are switched on/off (web interface syncs with Home Assistant switch). But when I switch WLED on/off from its web interface Home Assistant WLED switch doesn't turn on/off. I looked into Mosquitto topics with MQTT Explorer and found that WLED doesn't send on/off commands to mqtt broker from its web interface.

**Comment by timothybrown** [comment]
> Once again thank you very much for your project - great clean job.
> And thanks for adding long waited mqtt authentication support) Just checked and flashed last code - it seems authentication works fine, autodiscovery too. WLED appears in Home Assistant via Mosquitto. But I find one thing that doesn't work correctly - when I switch on/off WLED from Home Assistant wled web interface shows that leds are switched on/off (web interface syncs with Home Assistant switch). But when I switch WLED on/off from its web interface Home Assistant WLED switch doesn't turn on/off. I looked into Mosquitto topics with MQTT Explorer and found that WLED doesn't send on/off commands to mqtt broker from its web interface.

I'm actually working on this very issue right now! (My fix will be in a separate pull request and not this one.)

It will bring HA Discovery up to the current HA standard (WLED device will show up as an MQTT Integration, power status will work, etc.)

Look for it sometime this week.

**Comment by timothybrown** [comment]
Changes:

1) Added field in web UI to change the port.
2) Bumped username, password and client ID fields from 32 to 40 characters to accommodate specific brokers.

**Comment by Aircoookie** [comment]
Thank you so much for implementing this! I made a few security and quality-of-life adjustments. Please check if it still works as intended with HA! You might need to change the MQTT port back to 1883 in the settings, as I have changed the datatype from char* to uint16_t.
If everything works, I'll merge this PR and also create the 0.8.5 release soon :)

**Comment by timothybrown** [comment]
@Aircoookie Cool, I’ll give it a try shortly! Thanks for fixing up MQTT port stuff, I intended to go back and do that at some point (the char array was a 5 minute job to get it going for someone in the issue #198 thread).

All your other changes look good! I’ll report back shortly and verify everything compiles and connects.

**Comment by timothybrown** [comment]
@Aircoookie Your changes appear to work fine. After re-saving the port and rebooting it connects and stays connected as before. Consider this ready for deployment!

**Comment by sujitrp** [comment]
Made my day I was looking for this since long . With MQTT Authentication Now I can use latest version of Aircoookie /WLED :)

**Pull request merged**
