### PR TITLE
Adding Pixel Magic Tool to WLED

### PR DESCRIPTION
**Pull request by ajotanc**
It is a tool that converts any image into code in JSON WLED format, currently being tested on a 2D Matrix panel, soon I will post news for the serpentine version.

### Features
- Converts any type of image
- Option on tape address format
- Result output option
- Choice of brightness intensity
- Convert transparent pixels to chosen color
- Convert animated GIFs
- Resize image
- Select image direct from **[WLED-IP]/edit** or **upload**
- Can save, simulate, copy or download generated code

### CODE REVIEW

**Comment by blazoncek** [comment]
Please remove irrelevant changed files from PR. These include html_*.h except html_pxmagic.h.
I would also like you to try to get the colors consistent with WLED UI (if possible) and remove visual references for @ajotanc in UI. Leave the reference to @ajotanc  in comments of the source files.

**Comment by ajotanc** [comment]
> Please remove irrelevant changed files from PR. These include html_*.h except html_pxmagic.h. I would also like you to try to get the colors consistent with WLED UI (if possible) and remove visual references for @ajotanc in UI. Leave the reference to @ajotanc in comments of the source files.

How do I remove it from PR, they appeared as modified after inserting pxmaigc_*,
I will change the colors

**Comment by blazoncek** [comment]
Undo commit or revert to previous version by checking out HEAD~1 for those files.
You should've not committed them.

https://blog.gitnux.com/code/git-revert-file-to-previous-commit/
https://stackoverflow.com/questions/215718/how-do-i-reset-or-revert-a-file-to-a-specific-revision

**Do not just delete files and commit!!!**

**Comment by ajotanc** [comment]
> Undo commit or revert to previous version by checking out HEAD~1 for those files. You should've not committed them.
> 
> https://blog.gitnux.com/code/git-revert-file-to-previous-commit/ https://stackoverflow.com/questions/215718/how-do-i-reset-or-revert-a-file-to-a-specific-revision
> 
> **Do not just delete files and commit!!!**
> 
> EDIT: Do the above before you add any more commits.

Is it correct now?

**Comment by blazoncek** [comment]
Now that is completely wrong. You removed pxmagic while retaining incorrectly modified files.
Please close this PR and create a new one using only the files directly needed for pxmagic.

**Comment by blazoncek** [comment]
I'll try to fix this in the afternoon or over the weekend.

**Comment by ajotanc** [comment]
> Now that is completely wrong. You removed pxmagic while retaining incorrectly modified files. Please close this PR and create a new one using only the files directly needed for pxmagic.

ok, I'll keep looking.. Sorry, I didn't use github much, I'm starting to focus on it recently, I'm learning, soon I should be able to do things in it correctly.

**Comment by ajotanc** [comment]
If I make any changes to pxmagic, what do I need to do is just commit it?

**Comment by blazoncek** [comment]
> If I make any changes to pxmagic, what do I need to do is just commit it?

Update files (usually just pxmagic.htm) and commit changes, then push.
Once PR is merged you will need to make another PR to update. But that is just a matter of committing and pushing to your fork, then click "Make PR" on github.

**Comment by blazoncek** [comment]
Now everything looks correct and may be ready to merge.
There is an issue of sending smaller/larger image than segment size but that can be considered an edge case.

**Comment by ajotanc** [comment]
> Now everything looks correct and may be ready to merge. There is an issue of sending smaller/larger image than segment size but that can be considered an edge case.

Already corrected in this new commit I made! You can merge, hehe!

**Review by Aircoookie — APPROVED** [review]
This is cool!

**Comment by ajotanc** [comment]
> This is cool!

Thanks, bro!
I even made a new update, in this case to center the image inside the segment, if it is 20x20 and the image is 16x16, with 2 borders on each side, it was really cool!

Example of the image below, if it is interesting, I commit the new version.

image

**Comment by blazoncek** [comment]
@Aircoookie I am in favor of this being compiled in by default.

**Comment by ajotanc** [comment]
> @Aircoookie I am in favor of this being compiled in by default.

Thanks, that would be amazing 🥹💙

**Comment by ajotanc** [comment]
> Thanks for creating this, it's super cool! Will there be a way to access it from the frontend directly?

This question is only with @blazoncek or @Aircoookie to decide if it would be possible or not.

**Comment by blazoncek** [comment]
Find a good way and make a PR. I have no objections.
It may be hard to find a good spot in UI IMO.

**Comment by ajotanc** [comment]
> Find a good way and make a PR. I have no objections.
> It may be hard to find a good spot in UI IMO.

I'll see if I can do something, could you tell me which files should I move?

**Comment by ajotanc** [comment]
How do I put it as an option in the interface settings? For it to only appear if the person sets it to true.

**Comment by blazoncek** [comment]
> How do I put it as an option in the interface settings? For it to only appear if the person sets it to true.

You can edit `settings_ui.htm`and add pseudo configuration (`l`), then use it in `index.js` to work on it (`cfg`). But you can also make it global by changing quite a few CPP files (set.cpp, xml.cpp, cfg.cpp, etc).

**Pull request merged**
