### PR TITLE
Improve search and filter functionality

### PR DESCRIPTION
**Pull request by WoodyLetsCode**
I have improved the search and filter functionality.
Previously, when you searched for something, all elements containing the search word were displayed in alphabetical order.
Now the effects that start with the search word are displayed at the top.

Here are some screenshots:
Before | Now
-------- | --------
grafik | grafik
grafik | grafik

Now the filter doesn't put the emoji in the search bar anymore, and you can also filter for multiple options:
Before | Now
-------- | --------
grafik | grafik
was not possible | grafik

Before, when you selected a filter on a mobile device, the keyboard of your device opened. I fixed that as well.
Before | Now
-------- | --------
grafik | grafik

### CODE REVIEW

**Comment by blazoncek** [comment]
I'd prefer you worked on this in 0_15 branch.
0_14_1 *will not* receive enhancements like this.

**Comment by WoodyLetsCode** [comment]
Okay, tomorrow I will rebase it to 0_15 branch.

**Comment by WoodyLetsCode** [comment]
I noticed that the current implementation did not work correctly on Chrome. It threw this error:
grafik
I also fixed this, now the filter menu disapperas also on chrome.

**Comment by WoodyLetsCode** [comment]
The problem that the on-screen keyboard opens when a filter is activated has been _solved_ in v0.15 anyway, as filters are now linked to the search bar.

**Review by blazoncek — APPROVED** [review]
Approved.
It does increase flash usage by 151 bytes though.

**Pull request merged**
