### PR TITLE
Add send and receive groups to json api

### PR DESCRIPTION
**Pull request by shlomozippel**
I had a requirement to be able to set the send and receive groups dynamically based on a switch so I added the send & receive group bitmasks to the API / serialized state

### CODE REVIEW

**Comment by blazoncek** [comment]
No UI? Just API?

**Comment by shlomozippel** [comment]
There already is a UI for the group mask in the Sync settings screen

**Comment by blazoncek** [comment]
I know, I wrote it. 😄
I was wondering why do you need this API?

**Comment by shlomozippel** [comment]
This is for an art car at burning man - it has about 30 controllers on it running WLED. I wanted them all to have identical configuration and only change the send / recv group based on a switch. That way if controllers need to be swapped out it's easy to do and change their group with DIP switch or similar. Basically avoid requiring a phone / tablet / computer whenever possible.

This PR let me set the group mask with a preset that was activated by GPIO

**Comment by blazoncek** [comment]
If you want this merged then please update WLED knowledge base as well.
[WLED-Docs](https://github.com/Aircoookie/WLED-docs)

**Pull request merged**
