### PR TITLE
New Usermod: Clap Control (Smack That Usermod)

### PR DESCRIPTION
**Pull request by ChuckMash**
Clap Control
---
Control WLED with Clapping / Tapping / Knocking

Settings
---
* Enable
  * Enable/Disable Clap Control.
* Clap Timeout (ms)
  * How much you can delay between claps before Clap Control will assume the clapping has ended and act accordingly.
* Bounce Delay (ms)
  * Helps remove multiple activations in a very short time due to bounce.
  * Acts as a cooldown after a clap is detected. If unsure, leave as is.
* Serial Output Level
  * Sends Clap updates over serial connection as JSON.
  * 0: Disabled
  * 1: Send Clap update when preset is applied.
    * Example: {"claps":3,"preset":1}
  * 2: Send Clap update even when preset is not applied.
    * Example: {"claps":2}
    * Example: {"claps":3,"preset":1}
* Pin
  * Pin to read from for sensor
* Invert
  * Default is detect on LOW, invert to detect on HIGH
* N Clap(s)
  * Specify a preset to load when N clap(s) are detected

Supported Sensors
---
* FC-04 sound sensor Module
* SW-420 Vibration Sensor Module (inverted)
* Any sensor that pulls LOW when activated (or HIGH if Invert is enabled) 

Demo
---
[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=mRhMShXGT5s)
https://www.youtube.com/watch?v=mRhMShXGT5s

---
---

Looking for feedback before requesting merge

### CODE REVIEW

**Comment by ChuckMash** [comment]
will be renamed "Smack That Usermod"

**Comment by blazoncek** [comment]
You can reuse button logic (no need for pin allocation).
Also, use PROGMEM string constants to optimize flash/RAM use.

**Comment by ChuckMash** [comment]
> You can reuse button logic (no need for pin allocation). Also, use PROGMEM string constants to optimize flash/RAM use.

Thanks for the feedback, PROGMEM makes sense and will be implemented.

Can you elaborate on what you mean about reusing button logic?

**Comment by blazoncek** [comment]
You did not allocate GPIO used by usermod (usually done in setup()) so it may be used by some other part of WLED or anothere usermod. Also if UI fails allocation checks your usermod may use already allocated pin.

By button logic I may have been mistaken. I did not read the code thoroughly and did not see multiple claps trigger different presets. Please, disregard.

**Comment by ChuckMash** [comment]
Closing this PR, as I seem to have bungled something.
Will add another PR for this Usermod once it's ready.

**Pull request closed without merging**
