### PR TITLE
Create esp32_V4_eth environment and add wesp32 r7 board support to it.

### PR DESCRIPTION
**Pull request by bikerglen**
This pull requests creates an esp32_V4_eth environment that enables wired Ethernet connections with version 4 of the ESP32 IDF and adds support for the WESP32 Rev 7 hardware that uses the RTL8201 Ethernet PHY.

* Add esp32_V4_eth environment to support wired Ethernet with the ESP32 IDF v4.

* Add WESP32 rev 7+ Ethernet board type but only when compiling with the ESP32 IDF version 4 or higher.

* Change Ethernet menu options on Wi-Fi settings page to distinguish between rev 6 and older vs rev 7 and newer WESP32 boards.

* Only enable the menu option for WESP32 rev 7 hardware when using the ESP32 IDF v4 or newer.

### CODE REVIEW

**Comment by bikerglen** [comment]
I'm seeing one issue with the esp32_V4_eth environment:

After uploading the firmware.elf image, the default LED output is GPIO16. The color picker, sliders, palettes, etc., in the left hand pane of the GUI works as expected.

After configuring the Wi-Fi network or configuring the Ethernet network, the color picker, sliders, palettes, etc., in the left hand pane of the GUI all have their display attribute set to 'none' and are not displayed.

Going into the LED configuration screen shows the default LED output on GPIO64. 

After changing this back to GPIO16, GPIO33, etc., all the color picker stuff works normally again.

I do not know why the default LED output pin is changed when the Wi-Fi / network settings are saved. If you can give me hints as to where to look, I can dig into the code.

This issue does not occur with the esp32_eth environment.

**Comment by blazoncek** [comment]
Looks good to me but I lack hardware to do any testing.

You can override default LED pin by defining `-D LEDPIN=x` but if I see it correctly GPIO16 is allocated for Ethernet. Is it not?

I did have issues with LittleFS (saving/loading presets) in IDF 4+. So make sure you test that thoroughly.

**Comment by bikerglen** [comment]
Correct. GPIO16 is allocated correctly initially then gets changed to something out of bounds after saving the network configuration with IDF 4+. Seems like it could be a LittleFS issue to me too. I'll dig out some LED strings and check saving / loading presets this morning.

**Comment by blazoncek** [comment]
> Correct. GPIO16 is allocated correctly initially then gets changed to something out of bounds after saving the network configuration with IDF 4+. Seems like it could be a LittleFS issue to me too. I'll dig out some LED strings and check saving / loading presets this morning.

You *need* to override LED GPIO if Ethernet uses GPIO16.

**Comment by bikerglen** [comment]
Ah, got it! This is getting complicated.

If only Wi-Fi is configured:
- Select the WESP32 board in **either the existing esp32_eth environment or the new esp32_V4_eth environment** and save the settings.
- Ethernet fails to initialize (GPIO16 already allocated to strip).
```
initE: Attempting ETH config: 11
PIN ALLOC: FAIL: IO 16 already allocated by 0x82 (130)
```
- Color palettes are shown and work.

Reboot and if a WESP32 board is configured **and** Ethernet is successfully initialized:
- Ethernet initializes and grabs GPIO16.
- BusDigital fails to grab GPIO16 since Ethernet already has it.
```
PIN ALLOC: Pin 16 already allocated by 0x81 (129)
```
- The pin for the LEDs is set to 64 and the color palettes get a display: none style and don't work

And, of course, if Ethernet is not successfully initialized, the Ethernet pins are deallocated and BusDigital gets it and the color palettes work.

I agree. This is a pin allocation / pin conflict issue. Unfortunately, I don't think the issue is as is simple as grab a pin not used by any of the Ethernet boards (e.g. GPIO13) and add a `-D LEDPIN=13` to the build arguments in platformio.ini.

Moving the default pin away from GPIO16 is likely to change the default behavior for every board out there other than the relatively rare WESP32 board. Consider the case where a new user buys a low-cost Ethernet board that was designed assuming GPIO16 was the default pin. If that gets changed, the board no longer just works out of the box.

I'm more inclined to label this as known issue with WESP32 boards than break the past n years of default behavior for all the other Ethernet boards out there. The options going forward:

1) leave as is
2) add `-D LEDPIN=13` only to the new esp32_V4_eth environment.
3) add `-D LEDPIN=13` to both the old esp32_eth and new esp32_V4_eth environments.

My preference is (1) but it's your call.

**Comment by blazoncek** [comment]
GPIO16 is a bit controversial. It is the same pin on Wemos D1 mini compatible ESP32 boards as is D4 (GPIO2) on original Wemos D1 mini boards. Since both Quindor's Dig controllers and Serg74's wemos shields were compatible with both (ESP32 and ESP8266) it was chosen as default GPIO for ESP32. Check `const.h`

Unfortunately ESP32 with PSRAM uses GPIO16 for SPI RAM (PSRAM) and cannot be used and needs override. Check `platformio.ini` for existing overrides.

There was a lengthy discussion about that in the past.

**Comment by bikerglen** [comment]
Ok, I'm going to add a `-D LEDPIN=13` to both the old `esp32_eth` and new `esp32_V4_eth` environments. None of the existing Ethernet boards have a conflict with pin 13.

**Comment by josephhajduk** [comment]
I tried this on my hardware and it is working.

**Comment by bikerglen** [comment]
Thanks, @josephhajduk. I have four boards running this in my front yard right now as well with no issues.

**Comment by blazoncek** [comment]
Please rebase this PR for 0_15 branch so it can be considered for merging.

**Comment by skerner-dev** [comment]
Hey Devs,

unfortunately there was no reaction from @bikerglen yet, right? Any chance we can realize this PR for version 15 without Glen rebasing?

WLED is still running perfectly on wesp32 rev. 7 Boards.

Thanks!

**Comment by blazoncek** [comment]
> Any chance we can realize this PR for version 15 without Glen rebasing?

no

**Comment by bikerglen** [comment]
I'll see what I can do this weekend. It'll probably be on a new fork and with a new PR.

**Comment by blazoncek** [comment]
> I'll see what I can do this weekend. It'll probably be on a new fork and with a new PR.

just pull 0_15 into your branch, fix issues and push. the change merge branch (I can do that too)

**Comment by skerner-dev** [comment]
Hey Devs, Hey @bikerglen,

any update on your PR? I really appreciate your work. It would be cool to see the wesp boards > rev. 7 to be supported again in version 15.

**Comment by skerner-dev** [comment]
Hey @bikerglen 

any update on your PR? Would really be sad to not see your nice work implemented in version 15. My wESP32 boards are still running and i would love to be ready to update.

**Comment by bikerglen** [comment]
> Hey @bikerglen
> 
> any update on your PR? Would really be sad to not see your nice work implemented in version 15. My wESP32 boards are still running and i would love to be ready to update.

I'm out of town this week and am changing day jobs over the next few weeks so time is a bit tight. Also trying to finish a Zigbee project. I do have some new hardware I need to test that uses the wesp32 r7 board and when I test that hardware would be a good time for me to move everything to the latest and submit a new PR. Maybe I can bump up testing of the new hardware. Probably not what you want to hear.

**Comment by skerner-dev** [comment]
Hey Glen,

hope your are doing well. I wanted to ask about your PR again. It would be so nice if your changes could make it to the latest (and further) releas(es) of this fantastic project. Any chance you mitght do the PR?

Thanks!

**Comment by bikerglen** [comment]
HI, It’s getting to be light season and I have some new hardware I built last February that I want to use with the latest version of WLED and the WESP32 r7. I usually aim to set up all the lights during the US Thanksgiving long weekend. With any luck, I’ll be able to put together a new PR before then. -Glen

**Comment by josephhajduk** [comment]
Its about that time of year for me as well,  I have a number of WESP32 r7 I can test with if needed.

Regards,
Joseph

**Comment by bikerglen** [comment]
Thanks! Always good to have a 2nd person available to check things out!

**Pull request closed without merging**
