### PR TITLE
Added multi WiFi saving feature

### PR DESCRIPTION
**Pull request by JPZV**
## TL;DR:

This PR adds the Multi-Wifi saving feature, which was requested and discussed in #2845, #2974, #852, #1228, and other issues that I may not found.

### User's side
For the user I tried to make it as simple as possible: Now the WiFi setting page will have three "new" sections:
- _Connect to a new network_: Here the user can scan for a nearby network or add it manually with the option "_Other network..._"
- _Saved networks_: Here the user can manage its saved network by changing the SSID, the Password, or deleting it.
- _Addresses settings_: Here is the old DHCP/IP and mDNS settings. Sadly, this will affect to all networks, so, for example, setting a static IP to 192.168.0.64/24 while on _networkA,_ this will be used for every other network, even if the subnet of _networkB_ starts from 192.168.1.0/24. So, DHCP is fully recommended from now on if using multiple networks.

### In back-end
Nowadays WLED saves the WiFi setting in two global vars: _clientSSID_ and _clientPass_. Both are strings (well... Char array). Now, I removed these vars and created three new ones: _clientNetsSSID_, _clientNetsPass_ and _clientSavedNets_. The first two are almost the same as the old vars, but now they're Strings Array (or Char Matrix, or Char Array Array, or whatever you want to call it), which can save up to 5 Networks in ESP32, or 3 in ESP8266 (those limits were selected arbitrarily). While _clientSavedNets_ is a Byte that stores how many networks are saved and loaded into memory.

When WLED wants to connect to a network, it first scan for every nearby networks and start looking for the nearest saved network. Then, tries to connect to it, and if it can't, then try with the next near one. Each attempt has like 5 seconds before failing. This amount of time was selected because "Last reconnect too old" message was being fired immediately with anything greater than 5 seconds and with just one network.

### Backward compatibility
Now WLED will check if the config file has a network saved with the last scheme, and if there's, then it will add it as the _first network_ and then it'll save the config file with the new scheme

### Drawbacks
Because I'm not familiar with **Improv** and **EEPROM saving** in WLED, and because of backward compatibility concerns, in both cases it'll set/load the first network. For example:

```diff
-  readStringFromEEPROM(  0, clientSSID, 32);
-  readStringFromEEPROM( 32, clientPass, 64);
-  readStringFromEEPROM( 96,      cmDNS, 32);
+  readStringFromEEPROM(  0, clientNetsSSID[0], 32);
+  readStringFromEEPROM( 32, clientNetsPass[0], 64);
+  readStringFromEEPROM( 96,             cmDNS, 32);
```

This shouldn't be a big issue for most users, except for those who uses Improv/EEPROM and wanted to save multiple WiFi networks.

Also, as mentioned before, now the IP Settings will affect to every network, even if the subnets differs com each others.

## Files Changed:

- **cfg.cpp**: Now the WiFi settings will be saved as `ssid%d` and `psk%d`, where `%d` goes from 0 to 4, instead of `ssid` and `psk` respectively
- **const.h**: Added `WLED_MAX_SAVED_NETWORKS`, `SUBPAGE_MAIN_SETTINGS`, and `SUBPAGE_WIFI_NETWORKS` constant
- **data/settings_wifi.htm**: Added three new sections: _Connect to a new network_, _Saved networks_, and _Addresses settings_. Also, changed the `loadJS()` function to letting load more than one JS.
- **data/style.css**: Added `input[type="password"]` to the same `input[type="text"]` style.
- **fcn_declare.h**: Changed the declaration of `getSettingsJS` to `void getSettingsJS(byte subPage, char* dest, byte subSettings);`, so it can load sub-settings from the same page.
- **improv.cpp**, **set.cpp**, **wled.cpp** and **wled_eeprom.cpp**: Added support for multiple WiFi settings.
- **wled.h**:
  - Replaced `clientSSID` and `clientPass` global vars with `clientNetsSSID` and `clientNetsPass` respectively.
  - Added `clientSavedNets` global var.
  - Now `WLED_WIFI_CONFIGURED` will be true if the first network is configured, or if `clientSavedNets` is greater than zero.
- **wled_server.cpp**: Now the function `serveSettingsJS` will accept the `s` argument for loading sub-settings from the same page.
  - In case `s` is zero (default behavior). It'll return the `GetV` JS function. Otherwise, it'll return the `GetW` one.
- **xml.cpp**: Added support for `SUBPAGE_WIFI_NETWORKS` sub-setting in `SUBPAGE_WIFI` page. In this case, it'll return a tuple of three where the first item is the amount of saved networks, while the second item is the maximum amount of networks that can be saved, and the last item is an array of every saved network.

### CODE REVIEW

**Comment by blazoncek** [comment]
Thank you.
Please re-base this for 0_15 branch.

**Comment by blazoncek** [comment]
Something went wrong as there are 88 files changed. I cannot review that.
Can you please follow https://github.com/Aircoookie/WLED/wiki/How-to-properly-submit-a-PR and open a new PR? Select 0_15 branch when doing so.

**Comment by JPZV** [comment]
> Something went wrong as there are 88 files changed. I cannot review that. Can you please follow https://github.com/Aircoookie/WLED/wiki/How-to-properly-submit-a-PR and open a new PR? Select 0_15 branch when doing so.

Hi, yes! The rebase went extremely wrong, so I had to clone the 0_15 branch and patch all the files by hand. Right now I'm half way.

I'll open a new PR, so for now I'll close this one as it got corrupted. Sorry for that

**Comment by blazoncek** [comment]
Thank you!

**Pull request closed without merging**
