### PR TITLE
Add Home Assisant MQTT autodiscovery for usermod multi_relay.

### PR DESCRIPTION
**Pull request by herm**
See title.
Refs #2477.

### CODE REVIEW

**Comment by blazoncek** [comment]
Haha. 😁 Will check it out.
Unfortunately I do not use HA so no way of testing that part.

**Comment by blazoncek** [comment]
Please check the modifications and report back.

**Comment by herm** [comment]
Looks good to me. 
Tested and works fine.

**Comment by blazoncek** [comment]
Relay is a remote controlled switch, whereas switch may mean plain physical (rocker) switch.
I intend to keep term relay since it is also used in MQTT message broadcasts with other devices.

BTW I added ability for periodic broadcasts in case broker goes down for some reason.

Will be merging shortly.

**Comment by herm** [comment]
Periodic broadcast should not be required.
If the broker goes down we lose the connection and on reconnect (in `onMqttConnect`) the current state is published. The same happens when WLED loses the WIFI connection or reboot. If some other client loses the connection to the broker the broker has stored the retained message and will deliver it to the client. It's one of the nice things about MQTT that the application doesn't has to care about this kind of connection problems.

**Comment by blazoncek** [comment]
Not everyone is using Home Assistant (including me) and retained messages are something that should not hold operational states since they may not reflect current state.
Retained messages also pollute broker and a user needs to manually clean them if device is no longer available.
I checked several IoT devices I own and all of them periodically broadcast current state they are in.

**Pull request merged**
