### PR TITLE
Improve indent

### PR DESCRIPTION
**Pull request by Mattstir**
Improve indent, so its more aligned and correctly indented according to logic groups.

No functional change.

### CODE REVIEW

**Comment by Mattstir** [comment]
As this is my first PR for WLED wanted to start with something small ;) 
Do I also need to push the updated built `html_*.h` files? I'm asking because they changed a lot but IMO shouldn't just because of white space changes...
thx ;)

**Comment by Mattstir** [comment]
My guess as there is no feedback: There is no interesst in this simple improvement?

**Comment by Aircoookie** [comment]
Thank you very much for the contribution! :)
Lack of feedback is just due to limited time spent on WLED on my part in the recent past, it does not mean there is no interest, just that I hadn't taken a look yet.

**Comment by Mattstir** [comment]
Thanks for the feedback and the merge ;) I will consider more contributions in the future 🙌

**Pull request merged**
