### PR TITLE
Added ETH support for the cod.m WLED LAN Controller

### PR DESCRIPTION
**Pull request by UtechtDustin**
Added ethernet configuration for the upcoming cod.m WLED LAN Controller.

### CODE REVIEW

**Comment by UtechtDustin** [comment]
If a customer of us will reset the controller it's easier to find the correct config.

**Comment by softhack007** [comment]
> If a customer of us will reset the controller it's easier to find the correct config. Same thing like QuinLed-ESP32-Ethernet <-> TwilightLord-ESP32 Ethernet Shield.

Instead of adding a duplicate config, it's better to update the existing UI dropdown entry. 
-->  "ESP32-POE Ethernet or cod.m controler".

Case solved 😉

**Comment by blazoncek** [comment]
> Same thing like QuinLed-ESP32-Ethernet <-> TwilightLord-ESP32 Ethernet Shield

These were added at the time when space was not yet at premium (more than 3 years ago). Unfortunately removing them is a breaking change that may render devices unreachable.

**Review by blazoncek — CHANGES_REQUESTED** [review]
Adding a new type is only justified if it differs in HW configuration.

**Comment by UtechtDustin** [comment]
@blazoncek so can we rename the option as @softhack007 suggested ?   
That was also our first idea, but that could end up in something like that `ESP32-POE Ethernet or cod.m controller or xyz controller or foobar ETH controller`.

**Pull request closed without merging**
