### PR TITLE
Enable ESP watchdog by default

### PR DESCRIPTION
**Pull request by poelzi**
Use the ESP watchdog to detect hanging ESP and reset the firmware.
Can be disable by defining WLED_WATCHDOG_TIMOUT 0
Default timeout is 3 seconds on ESP32 and something on ESP8266 (currently ignored)

This will at least help with cases of some locked up controllers, but does not fix the underlaying problem.

### CODE REVIEW

**Comment by poelzi** [comment]
I tested this by adding a endless loop, but have now experienced the watchdog work in RL. Animation stopped, some seconds later the node started with default settings.

**Comment by blazoncek** [comment]
Rather than blindly enable WDT it woud be better to determine **where** the original WDT starvation occurs.
Normally all non customized code should feed the WDT on regular basis.

Still, having a flexibility to set WDT manually may be a good idea for those rare exceptions.

**Comment by poelzi** [comment]
Of course, deadlocks and other problems should be fixed, but having a dead controller is ofter even more problematic. The timeout is so large, that custom code does not need to feed it, but finishing the loop is enough.

**Comment by poelzi** [comment]
Esphome for example enables the watchdog.
https://github.com/esphome/esphome/blob/71fe2f7ed334c84d209fd641ec99bd090e1b79da/esphome/components/esp32/core.cpp#L41

Pretty common on Microcontrollers.

**Comment by poelzi** [comment]
@blazoncek Interesting. I was able to fix this by disableing the watchdog when OTA is initiated.

**Comment by blazoncek** [comment]
It works now. Thank you.
After a bit of additional testing I'll give it a go.

**Comment by blazoncek** [comment]
I am not sure if my ESP is experiencing brownouts (since I have detector disabled) but sometimes it freezes and WDT is not resetting it.
Any ideas?

**Comment by blazoncek** [comment]
Approved from my side.

**Comment by blazoncek** [comment]
After using this on both ESP8266 and ESP32 without issues (and benefiting from WDT lockup prevention) I think it is a worthy addition.

**Pull request merged**
