### PR TITLE
HA Light Auto Discovery

### PR DESCRIPTION
**Pull request by debsahu**
- Send HA MQTT Discovery message ~2.4kB based on input by @YeonV from here: https://github.com/Aircoookie/WLED/issues/131

### CODE REVIEW

**Comment by debsahu** [comment]
Fixed PIO/TravisCI as well https://travis-ci.com/debsahu/WLED/builds/104834062

**Comment by Aircoookie** [comment]
Thank you very much for your work! So if I understood this correctly, HA is now able to detect WLED devices without further user setup (creating config as in #131 manually)?
For now, I disabled it by default, because the string constants use some 2kB of global memory, and I'm really running low at the moment with high LED counts. But I agree, I will re-implement the getModeName() with the flash strings from the original WS2812FX and then I should be able to enable this by default! Also thanks for PIO and travis fixes!

**Comment by debsahu** [comment]
yes that is the idea, HA should be able to detect WLED automatically. You will reclaim ~2.4kB memory back after the function call.

**Comment by debsahu** [comment]
Just pushed getmodeName() and getModeCount() additions.

**Comment by YeonV** [comment]
OMG, thanks so much! Feeling so honored that you make my noobish things useful <3
Also thanks for the mention :)
Do we need to add YYYY (discovery topic) and XXXX (device name) to the web interface so one could set that from the frontend?

You did a great job mate!

**Comment by debsahu** [comment]
@YeonV Both YYYY and XXXX are already on web-interface. YYYY can be set on Sync Settings and XXXX is the friendly name you provide in the settings as well.

**Pull request merged**
