### PR TITLE
Usermode for the remotes

### PR DESCRIPTION
**Pull request by Mariu86**
Hello @Def3nder thanks for the great work. I have a request, can you implement an user mod for all the remotes you have in your fork to the original wled ? Thanks again.

### CODE REVIEW

**Comment by Def3nder** [comment]
Hi @Mariu86 , yes, I'm sure I can.

What exactle should I do ?

I tried to separate my changes a little bid in my fork, but for the IR-remotes I did not...

So do you mean the changes only for the IR mode selection that I described here https://github.com/Def3nder/WLED/releases/tag/v0.8.6-solid2 ?

I am quite new to the github stuff - so maybe you can tell me the best way in getting this done ?
(get this pull-request, updating my changes and pushing it back to the upstream origin, ...)

**Comment by Mariu86** [comment]
I am a noob at this. I have a few remote controls that I want to use with wled but they are not implement yet in the original Aircoookie/Wled and I see you have 4-5 remotes already implemented in your fork ( this it's what I need for me to use with original Wled and digital LEDs strips ) and I think

**Comment by Def3nder** [comment]
Hi @Mariu86 , I think this does not work the way you think it does.

You requested to merge to master from my fork to the upstream master (from Aircoookie).
But I do have several changes in my master - not only the IR-remotes.

Please cancel this pull-request and I will try to separate the changes for the IR-remotes into a branch and create a pull request for this new branch.

**Comment by Def3nder** [comment]
...by the way: the changes to IR remotes cannot be implemented as "Usermod" as they need to be implemented in **wled20_ir.ino**. Same applies for the solid (analog) RGB stripes - this needs to be implemented in **NpbWrapper.h**. 

So merging this into upstream master would work, but creating a usermod not.

**Comment by Aircoookie** [comment]
Thank you for the huge pull request!
Still need to see which of the changes I would like to add to master.
Unfortunately I can't merge this since there are a few changes required and I don't have write access to the PR (there is a box for that when you create the PR).

For now one thing I would definitely like to add is the support for analog strips :)
If you'd create a separate pull request for each feature you'd like to add, that would make it a lot easier for me to review, approve, if neccessary change, and merge your work!
I would be very grateful if you open a new PR with just the changes to `NpbWrapper.h` for now.

Thank you for contributing to WLED and have a very happy holiday :)

**Comment by Def3nder** [comment]
Hi @Aircoookie , unfortunately I did not open this PR myself - @Mariu86 did this because he liked my changes.

I will separate the changes into single branches ...but do not exactly know how to do this.
I knwo which of my changes in the master are for what feature - do you know how to separate this changes into a new branch so that I can use this new branch for the PR ?

**Comment by Mariu86** [comment]
Sorry I don't know how the pull request work. I will close the pull request thanks @Def3nder and  @Aircoookie for the great work! Thanks

**Pull request closed without merging**
