### PR TITLE
Fix missing header from HTTP requests

### PR DESCRIPTION
**Pull request by blazoncek**
Add HTTP header to requests made for JSON.

### CODE REVIEW

**Review by Aircoookie — APPROVED** [review]
Nice, good practice to always include the header even if not technically required.
Also, kudos on getting rid of `html_*.h` on GitHub!
I swear, that needlessly caused 95% of merge conflicts in PRs.

**Comment by blazoncek** [comment]
> Also, kudos on getting rid of `html_*.h` on GitHub! I swear, that needlessly caused 95% of merge conflicts in PRs.

That was @WoodyLetsCode . Node is beyond my capabilities.

He earned a special status with all the PRs he made IMO.

**Comment by WoodyLetsCode** [comment]
Thanks for your work! ❤️ But I have a few questions about this PR:
Why do you want to add this header for GET requests? Isn't that totally unnecessary for GET requests? Or what should the WLED server be able to do with this additional information from the header? Also in [RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.5) there is nothing about using the `Content-Type` header for GET requests, so I don't understand the point why this should be good practice? The [RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.5) only states that messages containing a payload body should generate a `Content-Type` header field.
I therefore only see an increase in traffic by a few bytes. Or am I seeing this wrong? 🤔

**Comment by blazoncek** [comment]
I guess you know better than I. 😄

**Comment by WoodyLetsCode** [comment]
So unless there is a specific reason, I would not add this header to the GET request. Same for the `charset` header. 🙂 
But that's just my opinion. Do what you think is best. 😃

**Comment by blazoncek** [comment]
If that sounded sarcastic it was not. I meant it.
You are way better than me as far as that goes.

**Comment by WoodyLetsCode** [comment]
All good! 😄  I didn't take your message sarcastically.

**Pull request closed without merging**
