### PR TITLE
fixed refs to removed usermod

### PR DESCRIPTION
**Pull request by ingDIY**
cleaned up old references to "USE_ALT_DISPlAY" that aren't used anymore in the code/source files
fixed readme.md documents and updated instructions
removed referencies to old usermods

### CODE REVIEW

**Comment by blazoncek** [comment]
You are not following: https://github.com/Aircoookie/WLED/wiki/How-to-properly-submit-a-PR

Why do you keep editing `0_15` branch? Create a PR from your branch where changes are made. And squash commits before opening PR.

**Comment by ingDIY** [comment]
> You are not following: https://github.com/Aircoookie/WLED/wiki/How-to-properly-submit-a-PR
> 
> Why do you keep editing `0_15` branch? Create a PR from your branch where changes are made. And squash commits before opening PR.

when I follow the wiki, this happens:

**Comment by ingDIY** [comment]
@blazoncek I didnt found a way to open the PR

**Comment by blazoncek** [comment]
You are apparently not doing things right. I do not know which step you missed. Did you push your changes?

**Pull request closed without merging**
