### PR TITLE
FX updates, 2nd try.

### PR DESCRIPTION
**Pull request by blazoncek**
- Ripple (2D & no Bg)
- Glitter (no Bg)
- Sparkle (no Bg)
- Scan (no Bg)
- Two dots (no Bg)
- ICU (no Bg)
- Lightning (no Bg)
- Halloween eyes (no Bg)
- Spots (no Bg)
- Bouncing Balls (no BG)
- Popcorn (no Bg)
- Starburst (no Bg)
- Drip (no Bg)
- Whitespace cleanup
- draw_circle()

"no Bg" will allow overlapping segments if checked.

### CODE REVIEW

**Comment by softhack007** [comment]
I'll take a look over the weekend 👍 

One idea: instead of calling it "No Bg" (technicially correct), you could name the option "Transparency" or "Overlay". Because I think that will make more sense from users perspective.

Question: will it require "global led  buffer", or can be used regardless of LED buffer settings?

**Comment by blazoncek** [comment]
"Overlay" may be a good alternative to "No Bg". 👍 

No double buffering is required. It just removes painting background so the effect is painted on top of underlying content.

**Comment by blazoncek** [comment]
https://user-images.githubusercontent.com/7722392/211052453-b6cfe705-ac7c-4d68-9eb5-95a9b74b8e34.MOV

Plasma overlaid with Drip.

**Comment by blazoncek** [comment]
@drhideg would that work instead of #2933 ?

**Review by Aircoookie — APPROVED** [review]
This appears to work great, thanks! :)

In the future we could mostly automate toggling between BG and overlay modes by checking if the segment partly overlaps with any previous segment, but there are a few edge cases where it might not work correctly (e.g. segments whose start and stop do overlap, but their grouping and spacing settings still cause them to have no overlapping/shared LEDs, therefore I think for now manual overlay toggling is a good solution.

**Comment by blazoncek** [comment]
@softhack007 when you think it is OK, just merge it.

**Comment by drhideg** [comment]
Nice job, especially eliminating the flickering.
I miss the option of changing the color of the flashing pixel from the `Glitter` overlay.
If you allow me, I would suggest a few changes where I removed the `Solid Glitter` and save a few bytes because the same effect can be achieved without it:

```diff
diff --git a/wled00/FX.cpp b/wled00/FX.cpp
index 8678929d..290bbb62 100644
--- a/wled00/FX.cpp
+++ b/wled00/FX.cpp
@@ -2913,35 +2913,22 @@ uint16_t mode_sinelon_rainbow(void) {
 static const char _data_FX_MODE_SINELON_RAINBOW[] PROGMEM = "Sinelon Rainbow@!,Trail;,,!;!";
 
 
-// utility function that will add random glitter to SEGMENT
-void glitter_base(uint8_t intensity, uint32_t col = ULTRAWHITE) {
-  if (intensity > random8()) {
-    if (SEGMENT.is2D()) {
-      SEGMENT.setPixelColorXY(random16(SEGMENT.virtualWidth()),random16(SEGMENT.virtualHeight()), col);
-    } else {
-      SEGMENT.setPixelColor(random16(SEGLEN), col);
-    }
-  }
-}
-
 //Rainbow with glitter, inspired by https://gist.github.com/kriegsman/062e10f7f07ba8518af6
 uint16_t mode_glitter()
 {
   if (!SEGMENT.check2) mode_palette();
-  glitter_base(SEGMENT.intensity);
-  return FRAMETIME;
-}
-static const char _data_FX_MODE_GLITTER[] PROGMEM = "Glitter@!,!,,,,,Overlay;;!;;m12=0"; //pixels
 
+  if (SEGMENT.intensity > random8()) {
+    if (SEGMENT.is2D()) {
+      SEGMENT.setPixelColorXY(random16(SEGMENT.virtualWidth()),random16(SEGMENT.virtualHeight()), SEGCOLOR(1));
+    } else {
+      SEGMENT.setPixelColor(random16(SEGLEN), SEGCOLOR(1));
+    }
+  }
 
-//Solid colour background with glitter
-uint16_t mode_solid_glitter()
-{
-  SEGMENT.fill(SEGCOLOR(0));
-  glitter_base(SEGMENT.intensity, SEGCOLOR(1));
   return FRAMETIME;
 }
-static const char _data_FX_MODE_SOLID_GLITTER[] PROGMEM = "Solid Glitter@,!;Bg,Glitter color!;;;m12=0";
+static const char _data_FX_MODE_GLITTER[] PROGMEM = "Glitter@!,!,,,,,Overlay;Bg,Glitter color!;!;;m12=0";
 
 
 //each needs 19 bytes
@@ -7440,7 +7427,6 @@ void WS2812FX::setupEffectData() {
   addEffect(FX_MODE_HEARTBEAT, &mode_heartbeat, _data_FX_MODE_HEARTBEAT);
   addEffect(FX_MODE_PACIFICA, &mode_pacifica, _data_FX_MODE_PACIFICA);
   addEffect(FX_MODE_CANDLE_MULTI, &mode_candle_multi, _data_FX_MODE_CANDLE_MULTI);
-  addEffect(FX_MODE_SOLID_GLITTER, &mode_solid_glitter, _data_FX_MODE_SOLID_GLITTER);
   addEffect(FX_MODE_SUNRISE, &mode_sunrise, _data_FX_MODE_SUNRISE);
   addEffect(FX_MODE_PHASED, &mode_phased, _data_FX_MODE_PHASED);
   addEffect(FX_MODE_TWINKLEUP, &mode_twinkleup, _data_FX_MODE_TWINKLEUP);
```
```diff
diff --git a/wled00/FX.h b/wled00/FX.h
index 10d4ad51..3cab0cf2 100644
--- a/wled00/FX.h
+++ b/wled00/FX.h
@@ -227,7 +227,7 @@
 #define FX_MODE_HEARTBEAT              100
 #define FX_MODE_PACIFICA               101
 #define FX_MODE_CANDLE_MULTI           102
-#define FX_MODE_SOLID_GLITTER          103
+// #define FX_MODE_SOLID_GLITTER          103  // removed in 0.14!
 #define FX_MODE_SUNRISE                104
 #define FX_MODE_PHASED                 105
 #define FX_MODE_TWINKLEUP              106
```

**Comment by blazoncek** [comment]
@drhideg I know, but that is intentional at this stage.

**Comment by softhack007** [comment]
> @softhack007 when you think it is OK, just merge it.

Looks good for me, let's merge it.

**Pull request merged**
