### PR TITLE
Allow lower values for touch threshold

### PR DESCRIPTION
**Pull request by RobinMeis**
Solved issue https://github.com/Aircoookie/WLED/issues/4076 by allowing lower values for touch threshold

### CODE REVIEW

**Comment by blazoncek** [comment]
Once @dedehai gets back from vacation I hope he'll review and approve.

**Review by DedeHai — COMMENTED** [review]
Need to test, may lead to ghost detections

**Comment by RobinMeis** [comment]
> Need to test, may lead to ghost detections

For me it doesn't but shouldn't be a too big issue as you already can get ghost detections on ESP32-Wroom with inappropriate settings.

**Comment by DedeHai** [comment]
I tested the change, low values lead to ghost detections but that is probably ok, I did not notice any crashes in my tests (tested on S2). 
@RobinMeis your PR is missing changes to the second interrupt attachment here:
https://github.com/Aircoookie/WLED/blob/f6c47ac19cd9fc2b6b2861289b86f2ef963a329a/wled00/set.cpp#L292

apart from that I am ok with removing the 256 as a minimum base value.

**Comment by RobinMeis** [comment]
I have fixed this. For me, I also get ghost detections for very low values but didn't get any ghost detections within the last two weeks on two lamps with reasonable values.

**Comment by DedeHai** [comment]
looks good, gets my approval.

**Pull request merged**
