### PR TITLE
Added digital clock overlay

### PR DESCRIPTION
**Pull request by lodesmets**
I have added a new overlay that can be used to create a big 7 segment style overlay

The functionality has already been added. In the future I will also add some new effects to go with this overlay

### CODE REVIEW

**Comment by lodesmets** [comment]
I have added setting to change the amount of led in the : between the hours and minutes

**Comment by lodesmets** [comment]
Hey, any updates on adding this?

**Comment by blazoncek** [comment]
There is now a usermod (since early October) that enhances on clock display and adds multiple configuration options.

**Comment by blazoncek** [comment]
I recommend to close this PR as it has become impossible to merge it due to amount of changes to core WLED since submitting PR.
My other recommendation is (if the OP wants to resubmit PR based on newer core) to wait until 0.14 is released which will enable you to write usermod effects (or overlays) without touching WLED core.

**Comment by lodesmets** [comment]
> I recommend to close this PR as it has become impossible to merge it due to amount of changes to core WLED since submitting PR. My other recommendation is (if the OP wants to resubmit PR based on newer core) to wait until 0.14 is released which will enable you to write usermod effects (or overlays) without touching WLED core.

Ok I will close it

**Pull request closed without merging**
