### PR TITLE
rewrite adalight parser

### PR DESCRIPTION
**Pull request by badbadc0ffee**
Fix for #194

### CODE REVIEW

**Comment by Aircoookie** [comment]
Thank you for the fix! Really appreciated :)

@raptusis are you building from source and can test this? If not, no worries, but I'll be able to test it in two days time at the earlierst.

**Comment by badbadc0ffee** [comment]
BTW: the change was needed to connect our office x-mas tree to our Jenkins build farm. The LEDs flicker softly and change their color based on the result of our latest build...
I have also verified the function with AmbiBox on Windows and Hyperion on Linux.
tree
Merry christmas.

**Comment by raptusis** [comment]
> Thank you for the fix! Really appreciated :)
> 
> @raptusis are you building from source and can test this? If not, no worries, but I'll be able to test it in two days time at the earlierst.

OK thanks! I will try as soon as possible! :)

**Comment by Aircoookie** [comment]
Verified working for me with 54 LEDs! And way better than before, no flickers or lags. Thanks again :)

**Comment by Mariu86** [comment]
How do you use the adalight Aircoookie?

**Comment by raptusis** [comment]
Ok , all work very well ! 
Thanks badbadc0ffee ! 
Thanks Aircoookie !

**Pull request merged**
