### PR TITLE
Use MQTT to stream data to multiple devices

### PR DESCRIPTION
**Pull request by DasBasti**
I built a project where it is necessary to send a "picture" to multiple distributed devices. I used an MQTT broker to do that and added a usermod to allow to send binary color values to the strip over the MQTT broker and group channel.

### CODE REVIEW

**Comment by blazoncek** [comment]
MQTT is not very convenient for time critical operations.
Why not rely on UDP? Need 100% delivery even if that means out-of-band delivery?

**Comment by DasBasti** [comment]
I choose MQTT because this is used to send a static picture to a bunch of devices all over the internet at the same time.

It is not meant to be for real time animations.

**Comment by blazoncek** [comment]
Did you test this on ESP8266 with at least 1200 LEDs and 12 segments defined?

**Comment by DasBasti** [comment]
no, only ESP32 with 64 LEDs

**Comment by blazoncek** [comment]
> no, only ESP32 with 64 LEDs

Please do since I am currently hard pressed for time.
And observe available memory (heap).
You don't need actual 1200 LEDs attached to ESP, just define them in LED Setting page.

**Comment by DasBasti** [comment]
Tested with ESP8266 with MQTT_MAX_PACKET_SIZE=1024*4 and 1000 LED: Heap free 14.8kB
ESP32 1000LED: Heap Free 177.2kB

There was no animation running. Should I test with running animation?

**Comment by blazoncek** [comment]
15k is a quite low on the heap size.
For stable run there should be at least 18k free at any time.
How much do you get with 600 LEDs? And yes, create a large number of segments and run Fireworks Starburst effect on all of them.

**Pull request closed without merging**
