### PR TITLE
Allow to override the max segments setting when compiling

### PR DESCRIPTION
**Pull request by poelzi**
I ran into segment limits quite often, this allows to increase the number with a compile flag

### CODE REVIEW

**Comment by blazoncek** [comment]
This is not a good idea without some serious memory checks or workarounds in the background.
If you need more than 12 segments on 8266 without modifying memory allocation parts of the code, you are welcome to try my experimetal fork (used for many WLED enhancements, past and future) where the limit is 18 and 24.

**Comment by blazoncek** [comment]
You can see the effect of out-of-memory condition here: #1974

**Comment by poelzi** [comment]
@blazoncek I changed it, so it only is allowed on esp32. I'm using an ESP32 with ~1400 rgbw leds and 32 segments with no problem.

**Comment by blazoncek** [comment]
Due to recent changes in JSON parsing it will be possible to have 32 segments by default on newer builds on ESP32 and 16 segments on ESP8266.
You can close the PR since it may not be needed.

**Comment by XPloadED** [comment]
> Due to recent changes in JSON parsing it will be possible to have 32 segments by default on newer builds on ESP32 and 16 segments on ESP8266.
> You can close the PR since it may not be needed.

What do you mean by newer builds? I am using the latest 0.13 b2 but I am stuck with 16 segments on my ESP32.
32 would be Perfect for my project as I need exactly that amount.

**Comment by Cuacco** [comment]
Hi
I am trying to create a smile face using a LED matrix 16x16, I am tryting to create a usermod with my code, but  I have not beena ble to find a function that let me activate individual LEDs, I tried with segments (some to keep in black (off) and other to iluminate (on)) but I reached the limit of segments... any idea to explore or advice?

**Comment by blazoncek** [comment]
There is a [JSON API](https://github.com/Aircoookie/WLED/wiki/JSON-API#per-segment-individual-led-control) that allows individual pixels to be set.

**Pull request merged**
