### PR TITLE
Add Pakistan timezone

### PR DESCRIPTION
**Pull request by yousaf465**
Added Pakistan Standard Timezone

### CODE REVIEW

**Comment by blazoncek** [comment]
You should use 0_14 branch as your base for this PR.
And then make PR for 0_14 branch, not main. Aircoookie already changed that but there are other issues involved.

**Comment by Aircoookie** [comment]
Rebasing caused a merge conflict, I've added the new timezone manually. Thank you for the contribution!

**Comment by yousaf465** [comment]
> Rebasing caused a merge conflict, I've added the new timezone manually. Thank you for the contribution!

Now new builds have Pakistani time zone? @blazoncek including yours and serg74's ?

**Comment by Aircoookie** [comment]
Yes, all new 0.14 builds from now on will.

**Comment by softhack007** [comment]
> Now new builds have Pakistani time zone? @blazoncek including yours and serg74's ?

Even more than that. I've also back-ported the change into our Soundreactive fork v0.13.**3** - currently in beta.

**Pull request closed without merging**
