### PR TITLE
Added css property for momentum-scrolling IOS

### PR DESCRIPTION
**Pull request by GrumpyMeow**
On my iPhone there  was never any momentum-scrolling on the effects-tab.
With this single css property, it makes navigating the effects so much more pleasent.

### CODE REVIEW

**Comment by Aircoookie** [comment]
Hi and thanl you :)
Would it be okay if i included the line manually? The compressed HTML is not the most recent version, so I can't merge this easily.

**Comment by GrumpyMeow** [comment]
Ofcourse!

**Comment by Aircoookie** [comment]
Thanks very much!
I will take a look at your other PRs soon, so you'll get contributor status either way :)

**Comment by Aircoookie** [comment]
Added! Ah, now I also see how the HTML could be outdated, this PR was against the 'dev' branch (which actually makes sense, I need to merge in the changes from master more often)

**Comment by GrumpyMeow** [comment]
Yes indeed. I did branch of the "dev" branch.

**Pull request closed without merging**
