### PR TITLE
Updated references to Web UI dev docs

### PR DESCRIPTION
**Pull request by laserguru**
I've updated the 3 instances where the link appears so that they point to the relevant page on the new site

### CODE REVIEW

**Comment by laserguru** [comment]
Also I would suggest updating the link to the wiki on the Readme to point to kno.wled.ge, so that the first things users see when clicking through isn't a message saying they're on a deprecated documentation.
Since that is a very public page I'm keeping that as a separate PR so @Aircoookie and/or the team can individually review

**Comment by blazoncek** [comment]
This has to be updated in cdata.js not the .h files.
Please create new PR with changes in cdata.js.

**Comment by laserguru** [comment]
Didn't look closely enough at cdata.js   
Working on it!

**Comment by laserguru** [comment]
Done on PR [2203](https://github.com/Aircoookie/WLED/pull/2203)

**Pull request closed without merging**
