### PR TITLE
Support for ESP32-S3, and some improvements for -C3 and -S2

### PR DESCRIPTION
**Pull request by softhack007**
These changes allow to compile a working WLED for ESP32-S3. I've tested some basic functions like adding LED stripes, WiFi configuration, and running some effects - works as expected.

Espressif  IDF>= 4.4.2 is needed (using the latest from tasmota), and NeoPixelBus currently only works when using the latest `dev` of Makuna.

Actually I am not so happy about my modified UI files - I've changed the hardcoded limits, however this will also affect "classic" ESP32. My skills in JS are not so good - maybe someone finds a cleaner solution. 

The main challenge is that all ESP32 variants (classic ESP32, ESP32-C3, ESP32-S2, ESP32-S3) have different number of GPIO, and these even have different capabilities. ESP32-S3 has 48 GPIO, no input-only GPI; GPIO22 to GPIO32 are "forbidden", however GPIO06 to GPIO12 can be used; GPIO00, GPIO03, GPIO45 and GPIO46 are "straping PINS"; Serial TX = GPIO43, RX = GPIO44; USB-otg + JTAG use GPIO19 + GPIO20.

https://github.com/Aircoookie/WLED/issues/2735, https://github.com/Aircoookie/WLED/issues/1940,

### CODE REVIEW

**Comment by softhack007** [comment]
PS: just looked at the CI build - seems that some ESP8266 environments do not define "RX" and "TX". I'll try to find a workaround tomorrow.

Any way, i'd be happy to already receive feedback on my PR.

**Comment by blazoncek** [comment]
Don't worry. I'll have a look.

**Comment by blazoncek** [comment]
Had a look and it seems like Settings will need a bit involved GPIO handling in the future.
My recommendation would be to adapt Settings pages to be provided by available GPIO from WLED C/C++ code instead of relying on hardcoded values.

**Comment by softhack007** [comment]
I'll keep my branch up-to-date with 0_14. 
Please tell me once you are ready to merge this, so I can squash everything into one commit.

**Comment by softhack007** [comment]
changes for -S3 are integrated here: https://github.com/blazoncek/WLED/tree/esp32-s2

**Comment by softhack007** [comment]
closed in favour of https://github.com/blazoncek/WLED/tree/esp32-s2.

**Comment by softhack007** [comment]
Just a clarification note, as there were questions on this already:
This PR was closed without merging. However we have developed in parallel a more complete solution, that is already merged and included in WLED version 0.14.0. 

 For more guidance, look here:  
* https://github.com/Aircoookie/WLED/issues/2735#issuecomment-1250058041 (PlatformIO compile env)
* https://github.com/Aircoookie/WLED/issues/2735#issuecomment-1250072529 (bootloader for 8MB **qio** flash)

**Comment by rassel2000** [comment]
Will the ESP32-S3 4MB FLASH version also be supported?

**Pull request closed without merging**
