### PR TITLE
security updates

### PR DESCRIPTION
**Pull request by farmmanic**

### CODE REVIEW

**Comment by softhack007** [comment]
Hi, could you explain a bit about the background of this change? Is it the result of `npm audit fix`, or where do the changes come from? Maybe you did a penetration test?
Did you verify the modifications by test?

**Comment by farmmanic** [comment]
I setup some ci/cd security workflows. I only pushed the dependacies  so
far.  I did audit the binaries.  Cant automate those fixes yet. I'll setup
the pio auto build workflow later today. I'll be doing some other
automation lmk if you have any requirements.

**Comment by blazoncek** [comment]
Please follow [this](https://github.com/Aircoookie/WLED/wiki/How-to-properly-submit-a-PR) article.

**Comment by farmmanic** [comment]
I'm setting up ci/cd stuff today whatever you guys want. I have it set now
to update my fork. Then merge. Then I run the pio autobuild action before
It sends the pr.

I didn't think it would matter for the version upgrades but I was gonna
reach out before I sent any code altering pr.

Do you have a preferred branch you want me to send from/to?

**Comment by farmmanic** [comment]
sorry i didn't realize it was pushing everything. should have only pushed pr that i verified.

**Comment by softhack007** [comment]
@farmmanic 
* please remove any 'linter'that cannot check C, C++ or JavaScript. There is no python in the final WLED image, so we don't need python checkers like pylint or bandit or snyk.
* you propose to add some workflows that use "actions that are not certified by GitHub.". Please explain the purpose and added value of these actions.

**Comment by farmmanic** [comment]
You can delete this.
I'm sorry about that I was using scrips and testing automations. They went
a little off the rails.

**Comment by softhack007** [comment]
> went a little off the rails.

Hi @farmmanic I still find parts of your changes interesting, however as you say a lot of cleanup would be needed to extract the "usefull parts". As suggested by @blazoncek I'd also prefer if you make a fresh PR.

* start the PR from a branch in your repo instead of 'main'
* target the PR to our '0_15' branch
* this article also has some guidance: https://github.com/Aircoookie/WLED/wiki/How-to-properly-submit-a-PR

I'm closing this PR for now, hoping you'll find time to clean up your very interesting contribution.

**Pull request closed without merging**
