### PR TITLE
Add WLED_DISABLE_AP to completely disable the AP feature

### PR DESCRIPTION
**Pull request by FreezyExp**

### CODE REVIEW

**Comment by blazoncek** [comment]
This defies the purpose of WLED.
Use your own fork for that.

**Comment by FreezyExp** [comment]
Being able to just remove the unneeded functionality seems like it would not harm the main purpose of driving RGB installations.

**Comment by blazoncek** [comment]
Port WLED to Arduino if you want WiFi-less variant.
It should be *fairly easy*.

**Comment by FreezyExp** [comment]
The WIFI is still there and still works, I just don't need it to become it's own access point, hence the desire to be able to compile that out.

**Comment by Aircoookie** [comment]
This would always require hard-coding custom WiFi credentials at compile time (or use Improv, but I would certainly not put a bin without AP support on the installer), I don't think that is practical in 99% of cases.

**Comment by FreezyExp** [comment]
p.s. I calculated the space savings after removing other AP related strings & code:

#define WLED_DISABLE_AP // saves 2.57kb

**Pull request closed without merging**
